import type { Activity } from './plan-generator';
import type { Locale } from '@/lib/i18n/config';

export const FALLBACK_ACTIVITIES_EN: Activity[] = [
  {
    id: 'fallback-colour-sorting',
    title: 'Rainbow Rescue Mission',
    description: 'Your little one becomes a colour rescue hero, gathering mismatched household items and returning them to their matching colour homes. Socks, blocks, crayons, fruit — anything goes into the bowls.',
    age_min: 2,
    age_max: 4,
    goal_tags: 'independent_play',
    play_style_tags: 'building',
    routine_moment_tags: 'morning',
    time_minutes: 10,
    materials: '3-4 bowls or plates, a handful of colourful household items (odd socks, duplo bricks, crayons, plastic spoons, a banana, a tomato — whatever you can grab in 30 seconds)',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Grab 3-4 bowls and set them in a line on the floor. Put one coloured item in each bowl as a starter — a red sock in one, a blue block in another.',
      'Scatter 10-15 colourful items on the floor nearby. Say: "Oh no, all these things got mixed up! Can you rescue them and put them back in the right colour home?"',
      'Let your child pick up items and decide where they go. If they put something in the "wrong" bowl, that\'s fine — let them make the rules.',
      'When they\'ve sorted everything, tip the bowls out together and say: "Uh oh, they escaped again!" Most kids will happily re-sort two or three times.',
      'If they\'re still into it, suggest a new rule: "What if we sort by big and small this time?"'
    ]),
    parent_script: '"Oh no, all these colours got jumbled up! The red sock is lost — can you find where it lives? That bowl right there! Now can you rescue all the other things and get them home?"',
    fallback_if_refuses: 'No worries — just set the bowls on the floor and start sorting yourself. Narrate what you\'re doing in a playful voice: "Hmm, where does this blue block go?" Most kids wander over within a minute. If not, leave the bowls out and let them discover it on their own later.',
    easier_version: 'Use just two bowls with two very different colours (red and blue). Pick items that are clearly one colour so there\'s no tricky decisions.',
    harder_version: null,
    why_it_works: 'Grouping things by colour is one of the earliest "maths" skills — it\'s how kids start to notice patterns and categories. It also lets them work independently, making their own decisions about where things go, which builds confidence.',
    safety_note: 'Skip small items like marbles or coins for under-3s — stick to things too big to fit in a mouth.',
    category: 'cognitive',
  },
  {
    id: 'fallback-story-dice',
    title: 'Flip & Tell Story Cards',
    description: 'You and your child draw silly pictures on scraps of paper, flip them face-down, and take turns picking one to add the next bit of a ridiculous story. The worse the drawings, the funnier it gets.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'speech',
    play_style_tags: 'stories',
    routine_moment_tags: 'anytime',
    time_minutes: 15,
    materials: 'Scrap paper torn or cut into squares (junk mail works great), crayons or markers, a flat surface to spread them on',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Tear or cut paper into roughly 8-10 squares. They don\'t need to be neat — wobbly is charming.',
      'Each of you draws quick pictures on them: a sun, a dog, a banana, a spaceship, a puddle, a crown — whatever pops into your head. Stick figures are perfect.',
      'Flip all the cards face-down and jumble them up on the table.',
      'You pick the first card, flip it, and start the story: "Once upon a time, a very grumpy banana was walking down the road..."',
      'Your child picks the next card and adds a sentence. Help them along if they get stuck: "And then the banana saw a... (flip!) ...a spaceship! What happened next?"',
      'Keep going until someone declares "The End!" — the sillier the ending, the better.'
    ]),
    parent_script: '"I bet we can make the silliest story in the whole house. I\'ll go first — ready? (Flip a card.) Once upon a time, there was a very confused penguin who lost his shoes. Your turn — pick a card and tell me what happens next!"',
    fallback_if_refuses: 'Start telling the story yourself in an exaggerated voice, pausing at exciting moments: "And then the penguin saw something AMAZING behind the door... I wonder what it was..." Leave a card face-down in front of them. Curiosity usually wins. If not, just enjoy telling them a silly story — that\'s still great language time.',
    easier_version: 'Cut pictures from a magazine or junk mail instead of drawing. Or skip the cards entirely and just take turns adding to a story while you\'re in the car or at dinner.',
    harder_version: null,
    why_it_works: 'Making up stories helps kids practise putting ideas in order, using new words, and thinking about what comes next. The card-flipping adds a surprise element that keeps them engaged longer than open-ended storytelling.',
    safety_note: null,
    category: 'language',
  },
  {
    id: 'fallback-freeze-dance',
    title: 'Freeze Dance Party',
    description: 'Crank up some music and dance like nobody\'s watching — then freeze when it stops. The real magic is that it burns off a huge amount of energy and practises stopping on cue, which helps with transitions later.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'calmer_transitions',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 10,
    materials: 'A phone or speaker for music (any playlist your kid loves), enough clear floor space to dance without crashing into the coffee table',
    location: 'indoor',
    energy_level: 'high',
    steps_json: JSON.stringify([
      'Push furniture back to clear a dance zone. Doesn\'t need to be big — a few square metres is plenty.',
      'Put on something upbeat your child likes. Say: "When the music plays, we dance. When it stops — FREEZE like a statue! If you wobble, you pick the next silly pose."',
      'Dance together. Be ridiculous — flap your arms, spin in circles, wiggle your hips. The sillier you are, the more they commit.',
      'Pause the music suddenly. Hold your freeze and say "Staaatue!" in a dramatic whisper. Giggle at each other\'s poses.',
      'After 5-6 rounds, gradually pick slower songs. Say: "Now we\'re dancing in slow motion... like astronauts on the moon..."',
      'End with a very slow song and gentle swaying. This is the sneaky part — you\'re teaching them to wind down.'
    ]),
    parent_script: '"Dance party! When the music plays, show me your wildest moves. But when it stops — FREEZE! Don\'t move a muscle. Ready? Here we go!"',
    fallback_if_refuses: 'Start dancing by yourself, being as silly as possible. Most kids physically cannot resist joining a dancing parent. If they still don\'t want to, just let the music play in the background while they do their own thing — even bobbing their head counts.',
    easier_version: 'Skip the freeze rule entirely. Just dance together. That\'s still wonderful.',
    harder_version: null,
    why_it_works: 'Stopping your body mid-movement takes real self-control — the same skill that helps kids pause before grabbing a toy or calm down when you say "wait." Wrapping it in a dance party means they practise it over and over without it feeling like a lesson.',
    safety_note: 'Check the floor for toys, shoes, or anything slippery before you start. Socks on hardwood can be slippy — bare feet or grippy socks are safer.',
    category: 'physical',
  },
  {
    id: 'fallback-blanket-fort',
    title: 'Secret Reading Den',
    description: 'Build a cosy blanket cave together, crawl inside with a torch and a pile of favourite books, and read in your own little world. This one almost always becomes a bedtime request.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'connection',
    play_style_tags: 'stories',
    routine_moment_tags: 'evening',
    time_minutes: 20,
    materials: 'A blanket or two, sofa cushions or dining chairs for structure, a torch or fairy lights or a phone with the flashlight on, 2-3 favourite books, a pillow to lie on',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Drape a blanket over the gap between a sofa and a chair, or over a table. It doesn\'t need to be architectural — saggy is fine.',
      'Let your child stuff cushions and pillows inside. Say: "You\'re the builder — make it as cosy as you want."',
      'Switch on a torch or fairy lights inside. The change in lighting is the magic — it makes an ordinary room feel completely different.',
      'Crawl in together. Let your child pick which book to read first. Read in a softer voice than usual — the small space invites it.',
      'When you finish the books, just lie there for a minute. Ask: "What\'s the best thing that happened today?" The den makes these conversations easier.',
      'Leave the fort up if you can — they\'ll probably go back to it on their own.'
    ]),
    parent_script: '"Let\'s build a secret reading den — just for us. You pick the books that are allowed inside and I\'ll get the torch. Nobody else knows about this place."',
    fallback_if_refuses: 'Let them focus on building the fort — arranging cushions and draping blankets is a great activity all on its own. The reading often sneaks in once the fort feels "ready." If it doesn\'t, that\'s fine — they built something, and you were there.',
    easier_version: 'Drape one blanket over a table — instant den, no engineering required. Toss a pillow underneath and you\'re done.',
    harder_version: null,
    why_it_works: 'Small enclosed spaces feel safe and special to young kids — it\'s like having their own little world. Reading together in that cosy, quiet space strengthens your connection in a way that\'s hard to replicate on the sofa with the TV nearby.',
    safety_note: null,
    category: 'bonding',
  },
  {
    id: 'fallback-kitchen-band',
    title: 'Pots & Spoons Orchestra',
    description: 'Raid the kitchen cupboard for instruments — pots become drums, a whisk on a colander is a güiro, rice in a sealed container is a shaker. Take turns being the conductor who controls loud, soft, fast, and slow.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'focus',
    play_style_tags: 'moving',
    routine_moment_tags: 'morning',
    time_minutes: 10,
    materials: 'A couple of pots or saucepans, wooden spoons, a plastic container with a handful of rice sealed inside (shaker), a metal lid or baking tray (cymbal), a whisk',
    location: 'indoor',
    energy_level: 'medium',
    steps_json: JSON.stringify([
      'Pull out 3-4 "instruments" from the kitchen and set them on the floor: a pot and wooden spoon (drum), a sealed container with rice (shaker), a baking tray (cymbal).',
      'Give your child a wooden spoon. Let them bang on everything for a minute to get the wiggles out — this part is pure noise, and that\'s OK.',
      'Now introduce the conductor game: "When I hold my spoon up high, play LOUD. When I bring it down low, play as quietly as a mouse."',
      'Practise loud and soft a few times, then add fast and slow. Exaggerate your movements — kids love the drama.',
      'Switch roles. Say: "Your turn to be the boss of the band! I have to do whatever you say." Follow their lead enthusiastically, even when it\'s just "LOUD LOUD LOUD."',
      'Wind down by conducting a "lullaby" — get slower and softer until you\'re barely tapping.'
    ]),
    parent_script: '"We\'re starting a band! You\'re the drummer — here\'s your drumstick. When I hold my spoon way up high, play as LOUD as you can. When I bring it way down low, play so quiet that only a mouse could hear. Ready?"',
    fallback_if_refuses: 'Sit on the floor and start tapping out a gentle rhythm yourself. Don\'t invite them — just play. Hum along. Most kids pick up an instrument within a couple of minutes. If they don\'t, leave the "instruments" out. They might come back to them later.',
    easier_version: 'Skip the conductor rules entirely and just bang along together. Make up a silly song about what you\'re having for lunch.',
    harder_version: null,
    why_it_works: 'Watching someone and matching what they do — play loud when they signal loud, stop when they signal stop — is attention and impulse control in disguise. Kids don\'t notice they\'re practising because they\'re having too much fun being noisy.',
    safety_note: 'Keep breakable dishes and glass lids out of reach. Wooden and plastic items only.',
    category: 'sensory',
  },
  {
    id: 'fallback-treasure-hunt',
    title: 'Backyard Treasure Hunt',
    description: 'Make a quick treasure checklist together — a pointy leaf, something smooth, a tiny stick, anything that smells interesting — then head outside and let your child lead the expedition.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'independent_play',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 15,
    materials: 'A scrap of paper and a crayon for the checklist, a bag or container for treasures (a reusable shopping bag works great), shoes you don\'t mind getting muddy',
    location: 'outdoor',
    energy_level: 'medium',
    steps_json: JSON.stringify([
      'Sit down together and draw a quick checklist: a leaf, a smooth stone, a stick, something that smells nice, and something bumpy. Draw little pictures next to each one so your child can "read" it.',
      'Give them the bag and the list. Say: "You\'re the expedition leader. I\'m your assistant — tell me where to go."',
      'Follow their lead outside. Resist the urge to point things out right away — give them a good 30 seconds to look before you offer a hint.',
      'When they find something, tick it off the list together. Make a fuss: "A bumpy pinecone — brilliant find!"',
      'Once everything\'s ticked off, bring the treasures home and arrange them in a line from smallest to biggest, or make a little nature collage on a paper plate.',
      'Leave the collection somewhere visible. They\'ll probably tell the next person who walks in about their expedition.'
    ]),
    parent_script: '"We\'re going on a treasure hunt and YOU\'re the boss of the map. First on the list — can you find a leaf? Any kind of leaf. You lead the way and I\'ll follow!"',
    fallback_if_refuses: 'Simplify it to "find me three interesting things" — no checklist, no rules. Or start picking things up yourself and wondering aloud about them: "Ooh, this rock is so smooth. I wonder if I can find a rough one..." Kids often join in when it feels like exploring, not a task.',
    easier_version: 'Skip the checklist. Just bring a bag and collect anything they think is cool. Three treasures is a perfect number for younger kids.',
    harder_version: null,
    why_it_works: 'Being the "leader" gives kids a sense of ownership and independence. The checklist adds just enough structure to keep them engaged without turning a walk into a chore. And arranging their finds afterwards sneaks in early sorting and comparing.',
    safety_note: 'Stay within arm\'s reach near roads or water. Remind them to look with their eyes first before picking up anything spiky or unfamiliar. Leave other people\'s gardens alone.',
    category: 'outdoor',
  },
  {
    id: 'fallback-calm-down-jar',
    title: 'Calm-Down Glitter Jar',
    description: 'Make a sparkly jar together — warm water, a squeeze of glue, and a heap of glitter. Shake it up when feelings get big, and breathe together as you watch the glitter slowly drift to the bottom.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'calmer_transitions',
    play_style_tags: 'routine',
    routine_moment_tags: 'anytime',
    time_minutes: 15,
    materials: 'A clear jar or plastic bottle with a tight lid (a clean jam jar or old water bottle works), warm water, clear glue or glycerine (a small squeeze), glitter or sequins, strong tape or superglue to seal the lid',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Fill the jar about three-quarters full with warm water. Let your child help pour — a funnel or jug makes this easier and less messy.',
      'Squeeze in a blob of clear glue (about a tablespoon). This is what makes the glitter fall slowly instead of just dropping. Stir it in.',
      'Let your child spoon in glitter or sequins. More is more — let them go for it.',
      'Screw the lid on tight, then seal it with strong tape or a ring of superglue so it can\'t be opened. Wait for the glue to dry.',
      'Shake the jar together and watch the glitter swirl. Say: "See how everything\'s spinning around? Sometimes our feelings are like that — all swirly. Let\'s breathe and watch it settle."',
      'Take three slow breaths together while the glitter drifts down. Say: "By the time the glitter reaches the bottom, our bodies will feel calmer too."'
    ]),
    parent_script: '"Let\'s make something sparkly together. And here\'s the cool part — when you feel all fizzy inside, like when you\'re frustrated or everything feels too much, you shake this jar and watch the sparkles. By the time they reach the bottom, you\'ll feel a bit calmer. Let\'s try it!"',
    fallback_if_refuses: 'Make it a craft project first — "We\'re just making something sparkly." Skip the feelings conversation entirely. Once the jar exists, they\'ll shake it for fun, and the calming part happens on its own. You can always talk about feelings another day.',
    easier_version: 'Use a pre-made snow globe, or fill a clear bottle with water and a few drops of food colouring — shake it and watch the colour swirl and slowly clear.',
    harder_version: null,
    why_it_works: 'Watching something move slowly while you breathe gives your body a chance to switch from "alert mode" to "calm mode." It works for grown-ups too — try it. Having a physical object to reach for when feelings are big gives kids something to do with their hands instead of lashing out.',
    safety_note: 'Seal the lid properly — warm water plus glitter on the carpet is nobody\'s idea of a good time. Supervise younger kids around the superglue step.',
    category: 'emotional',
  },
  {
    id: 'fallback-block-tower',
    title: 'Tallest Tower in the House',
    description: 'Build the tallest tower you can together, one block at a time, taking turns. The suspense of "will it fall?" keeps them completely focused. When it crashes — and it will — cheer and start again.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'focus',
    play_style_tags: 'building',
    routine_moment_tags: 'anytime',
    time_minutes: 10,
    materials: 'Building blocks, duplo, or anything stackable (shoeboxes, toilet roll tubes, food tins from the cupboard — get creative)',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Tip all your blocks (or stackable items) into a pile in the middle of the floor. Say: "I bet we can build a tower taller than your teddy bear."',
      'Take turns placing one block each. Count out loud together as you go: "One... two... three..."',
      'Make it dramatic. Whisper as the tower gets tall: "Careful... careful..." Hold your breath theatrically when it wobbles.',
      'When it crashes, cheer! "EIGHT blocks! That was AMAZING! Can we beat eight this time?"',
      'After a few rounds, let your child build solo while you count and commentate like a sports announcer: "She\'s going for block number TEN, folks — incredible technique!"'
    ]),
    parent_script: '"Let\'s see how tall we can make this. You put one on, then I put one on. Ready? You go first — pick a good strong one for the bottom."',
    fallback_if_refuses: 'Build a tower yourself and let them be the one who knocks it down. Destruction is deeply satisfying at this age, and once they\'ve knocked a few down, they usually want to build one to smash. That counts.',
    easier_version: 'Build side by side instead of sharing one tower. No turn-taking pressure, and they can copy your technique.',
    harder_version: null,
    why_it_works: 'Waiting for your turn, even for just a few seconds, is genuine patience practice. And the physical act of stacking — lining edges up, balancing, adjusting — builds hand control and spatial awareness. The counting sneaks in some early number sense too.',
    safety_note: null,
    category: 'cognitive',
  },
  {
    id: 'fallback-puppet-show',
    title: 'Sock Puppet Theatre',
    description: 'Raid the odd-sock drawer, draw on some faces, and put on a show together. Puppets let kids practise tricky social stuff — sharing, saying sorry, meeting someone new — without any real-world stakes.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'speech',
    play_style_tags: 'stories',
    routine_moment_tags: 'evening',
    time_minutes: 15,
    materials: 'Two odd socks (the rattier the better), a marker or felt-tip pen for faces, optional: googly eyes, buttons, yarn for hair, a sofa to hide behind as a "stage"',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Pull on a sock and draw two dots for eyes and a wobbly mouth. Say in a silly voice: "Hello! My name is Professor Sockface. Who are YOU?" Hand your child the other sock and a marker.',
      'Let them decorate their puppet however they want. Wonky eyes, three mouths, a scribble nose — it\'s all perfect.',
      'Start a simple scene with your puppet. Pick something familiar: "Professor Sockface is going to the shop. He needs to buy bananas but he can\'t find them anywhere! Can your puppet help?"',
      'Let your child take over the story. Follow their lead, even if it goes completely off the rails. If they get stuck, have your puppet ask their puppet a question.',
      'If they\'re into it, hide behind the sofa as a "stage" and perform for a stuffed animal audience.',
      'Leave the puppets somewhere visible — sock puppets have a way of reappearing at breakfast the next morning.'
    ]),
    parent_script: '"(In a high squeaky voice) Hello there! I\'m Professor Sockface and I\'m a bit confused. I can\'t remember where I left my shoes — which is funny because I\'m a sock! Do you think your puppet could help me?"',
    fallback_if_refuses: 'Use the puppet to talk to your child instead of talking directly. Kids who won\'t talk to you will sometimes chat happily with a puppet — it feels less direct. "Professor Sockface" can ask what they want for dinner or what happened at nursery.',
    easier_version: 'Skip the decorating — just put a sock on your hand and make it "talk." The simplest puppet is just your hand opening and closing.',
    harder_version: null,
    why_it_works: 'When a puppet says something, it doesn\'t feel like it "counts" the same way real words do — so kids will try out new phrases, work through scenarios, and practise conversations with much less self-consciousness than face-to-face.',
    safety_note: null,
    category: 'language',
  },
  {
    id: 'fallback-obstacle-course',
    title: 'Living Room Obstacle Course',
    description: 'Cushion stepping stones, a chair tunnel to crawl through, a tape line to balance on, and a pillow to jump over at the end. Time their runs — then let them rebuild it however they want.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'fewer_screens',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 15,
    materials: 'Sofa cushions, dining chairs, masking tape or painter\'s tape (for a balance line on the floor), a pillow for a jump landing zone, a timer on your phone',
    location: 'indoor',
    energy_level: 'high',
    steps_json: JSON.stringify([
      'Lay 4-5 sofa cushions in a wobbly path across the floor — these are stepping stones over "lava." Say: "Whatever you do, don\'t touch the floor — it\'s lava!"',
      'Set up two chairs with a gap to crawl through (the "tunnel"). Drape a blanket over for extra effect if you like.',
      'Stick a line of tape on the floor for a balance beam. About two metres is plenty.',
      'Put a pillow at the end as a landing pad for a victory jump.',
      'Walk through the course once yourself, narrating each bit: "Stepping stones, through the tunnel, walk the tightrope, and... JUMP!" Then say: "Your turn. I\'m timing you — ready, set, GO!"',
      'After three or four runs, hand them the power: "Now YOU design the course for ME." Whatever they build, do it with full commitment.'
    ]),
    parent_script: '"OK, here\'s the deal. The floor is lava, that\'s a tunnel, that\'s a tightrope, and at the end you jump onto the crash pad. I\'m timing you on my phone. Ready? Three... two... one... GO!"',
    fallback_if_refuses: 'Build the course and do it yourself — count your own time, huff and puff, dramatically struggle through the tunnel. Then casually say: "I got 14 seconds. I bet nobody could beat that." Walk away. Wait.',
    easier_version: 'Just the cushion stepping stones — no timer, no crawling, just "don\'t touch the lava" while moving across the room.',
    harder_version: null,
    why_it_works: 'This scratches the same itch as a screen — it\'s novel, exciting, and has a clear goal. But it also burns off physical energy, builds coordination, and gives kids a sense of accomplishment that outlasts the dopamine hit of another YouTube video.',
    safety_note: 'Make sure chairs can\'t tip over. Move anything sharp or hard away from the landing zone. Bare feet grip better than socks.',
    category: 'physical',
  },
  {
    id: 'fallback-bedtime-yoga',
    title: 'Sleepy Animal Yoga',
    description: 'Five gentle animal stretches that take your child from wiggly to winding down. Cat, butterfly, flamingo, sleepy bear, and curled-up hedgehog — each one a little calmer than the last.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'easier_bedtime',
    play_style_tags: 'routine',
    routine_moment_tags: 'bedtime',
    time_minutes: 8,
    materials: 'Nothing — just a bit of floor space next to their bed, and maybe a blanket to lie on',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Start standing. Say: "Let\'s be five sleepy animals before bed. First — a cat who just woke up from a nap." Get on hands and knees, arch your back up like a stretching cat, then dip it down. Do it three times, slow.',
      'Sit down on the floor together. "Now we\'re butterflies drying our wings in the sun." Feet together, knees out, gently flap your knees up and down. Breathe in when knees go up, out when they come down.',
      'Stand on one leg. "Flamingo! Can you balance without falling in the pond?" Hold arms out wide. Wobbling and giggling is the whole point.',
      '"Now we\'re a tired bear going back to our cave." Stand up, then slowly fold forward, letting your arms hang heavy like a bear\'s paws. Sway gently side to side.',
      '"Last one. We\'re hedgehogs curling up for winter." Lie down and curl into the smallest, tightest ball you can. Whisper: "Tiny hedgehog... so cosy... so sleepy..."',
      'Unroll slowly. Lie flat and take three big breaths together. If they\'re in bed now, tuck them in and say: "Even the hedgehog is asleep."'
    ]),
    parent_script: '"Time for sleepy animal yoga. We\'re going to be five animals, and each one is a bit sleepier than the last. First — show me your best cat stretch. Big stretch... biiiiig stretch... ahhhh."',
    fallback_if_refuses: 'Do the poses yourself beside their bed, narrating in a soft, slow voice: "I\'m a stretchy cat... now I\'m a butterfly..." Don\'t ask them to join. The gentle movement and quiet voice often pull them in. If they just watch from bed, that\'s fine — they\'re still winding down.',
    easier_version: 'Do just the last two poses lying in bed — sleepy bear (stretch arms up, then flop) and curled-up hedgehog (curl into a ball). Two minutes, done.',
    harder_version: null,
    why_it_works: 'Slow, predictable movements with deep breathing tell the body it\'s safe to relax. Moving through a sequence — especially one that gets progressively calmer — is much more effective at winding down than just saying "calm down please."',
    safety_note: null,
    category: 'routine',
  },
  {
    id: 'fallback-magic-drawing',
    title: 'Secret Picture Painting',
    description: 'Draw an invisible picture with a white crayon on white paper, then hand your child the watercolours and watch their face when the hidden picture magically appears under the paint.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'independent_play',
    play_style_tags: 'building',
    routine_moment_tags: 'morning',
    time_minutes: 12,
    materials: 'White paper, a white crayon (or a white candle stub — works even better), watercolour paints or watered-down food colouring, a chunky paintbrush, a cup of water, something to protect the table (newspaper, a bin bag, an old towel)',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'While your child isn\'t looking (or is busy with something else for a moment), press hard with a white crayon on white paper and draw something they\'ll recognise — a star, their initial, a cat face, a heart.',
      'Set out the paints, a brush, and the cup of water. Put the paper in front of them and say: "There\'s a secret picture hiding on this paper. The only way to find it is to paint over it."',
      'Let them paint however they want. As the colour goes over the wax, the hidden picture appears. Watch their face — this bit is genuinely delightful.',
      'Say: "You found it! It was a star! Want to make one for me now?" Hand them the white crayon and a fresh sheet.',
      'Let them draw their own secret picture (they\'ll press really hard, which is great for hand strength), then you paint over it to "find" it.',
      'Keep going as long as they\'re interested. This one has surprisingly long staying power.'
    ]),
    parent_script: '"I hid a secret picture on this paper. You can\'t see it yet — but if you paint over it, it\'ll magically appear. Grab the brush and let\'s find out what it is!"',
    fallback_if_refuses: 'Skip the secret picture part and just set out the watercolours for free painting. Most kids can\'t resist an open paint set. You can always try the hidden picture trick another day when the moment is right.',
    easier_version: 'You do all the drawing; they just paint to reveal. For very young ones, use a fat candle stub instead of a crayon — it\'s easier to grip and leaves a better wax resist.',
    harder_version: null,
    why_it_works: 'The surprise of watching something invisible appear holds attention far longer than regular painting. And pressing hard with the crayon, then controlling a wet brush across the page, builds the hand strength and control they\'ll need for writing.',
    safety_note: 'Cover your table and nearby floor — watercolours are washable but enthusiastic toddler painting reaches further than you\'d expect. Roll sleeves up or use an old shirt as a smock.',
    category: 'creative',
  },
  {
    id: 'fallback-puddle-splash',
    title: 'Puddle Kitchen',
    description: 'Head outside with cups, a funnel, and a spoon. Your child becomes a "chef" — stirring puddle soup, pouring between containers, testing what floats and what sinks. Messy, absorbing, and surprisingly long-lasting.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'independent_play',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 15,
    materials: 'Wellies and clothes you don\'t mind getting wet, 2-3 cups or containers of different sizes, a funnel if you have one, a spoon for stirring, a few small items to test (leaf, stone, stick, bottle cap, pine cone)',
    location: 'outdoor',
    energy_level: 'medium',
    steps_json: JSON.stringify([
      'Kit up: wellies, old clothes, jacket if it\'s chilly. Accept in advance that they will get wet. Say: "We\'re going to be puddle chefs today. Chef\'s hat on!"',
      'Find a puddle, or fill a washing-up bowl with water outside. Set out the cups, funnel, and spoon nearby.',
      'Start the play: "First, we need to make puddle soup. Can you stir it with the spoon? Now pour some into this cup — is it full yet?"',
      'Introduce floating and sinking: "Chef\'s challenge — which ingredients float in our soup?" Drop in a leaf (floats!), then a stone (sinks!). Let them test other items.',
      'Step back. Once they\'re pouring between containers and dropping things in, most children will happily play for 10-15 minutes without needing you to direct.',
      'When it\'s time to go in, give a two-minute warning: "Two more pours and then we go inside for warm socks." Follow through calmly.'
    ]),
    parent_script: '"We\'re puddle chefs today! First job — pour some water into this cup. Is it full? Now pour it into the big cup. Does it fill up? Let\'s make soup — what should we add? How about this leaf?"',
    fallback_if_refuses: 'Skip the structured stuff entirely. Just stomp in the puddle together. Once they\'re already outside and already wet, the cups and pouring often happen on their own. The goal is getting them outdoors — everything else follows.',
    easier_version: 'Just splash and stomp — no cups, no pouring, no science. That\'s plenty for younger toddlers and rainy days when you just need to get wiggles out.',
    harder_version: null,
    why_it_works: 'Water is naturally mesmerising for young kids. Pouring between containers is one of the best ways they learn about "more and less," "full and empty," and "heavy and light" — all foundational maths concepts that stick better through hands-on play than flashcards.',
    safety_note: 'Stay within arm\'s reach any time there\'s water involved. Get them into dry clothes quickly afterwards so they don\'t get cold.',
    category: 'outdoor',
  },
  {
    id: 'fallback-feelings-faces',
    title: 'Feelings Faces Gallery',
    description: 'Draw big blank circles on paper and turn them into faces together — happy, grumpy, surprised, silly, sleepy. Then stick them on the fridge so your child can point to how they\'re feeling when words aren\'t enough.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'calmer_transitions',
    play_style_tags: 'building',
    routine_moment_tags: 'anytime',
    time_minutes: 10,
    materials: 'Paper (one sheet is enough), crayons or markers, tape or a magnet to stick them on the fridge',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Draw 5-6 big empty circles on a sheet of paper. (If you\'re feeling fancy, cut them out.) Say: "We\'re going to make a feelings gallery for the fridge."',
      'Start with an easy one: "Can you draw a happy face? What do happy eyes look like? What about the mouth?" Draw yours alongside — it doesn\'t need to be good.',
      'Move to other feelings: grumpy (eyebrows down, mouth like a zigzag), surprised (big round mouth, wide eyes), silly (tongue sticking out), sleepy (droopy eyes, yawning mouth).',
      'After each one, make the face together. "Show me your grumpy face! Grrrr. Now show me your surprised face! OH!" This part usually gets giggly.',
      'Tape them to the fridge at your child\'s eye level. Say: "Now whenever you\'re feeling something big, you can point to the face that matches. Even if you can\'t find the words, you can show me."',
      'Over the next few days, use them yourself: "I\'m feeling a bit grumpy right now — see, that face there? But I think a cup of tea will help." Modelling this is the most powerful part.'
    ]),
    parent_script: '"Let\'s draw some feelings faces for the fridge. You know what happy looks like — can you draw it? Big smile! Now what about a grumpy face? Show me with YOUR face first — oh, that\'s a very good grumpy face!"',
    fallback_if_refuses: 'Draw the faces yourself and let them just colour them in, add stickers, or circle the one that matches how they feel right now. Even pointing at a pre-drawn face is a win — the goal is giving them a way to communicate feelings, not creating art.',
    easier_version: 'Draw the faces yourself and print or cut them out. They just need to point to one. You can also use emoji stickers if you have them.',
    harder_version: null,
    why_it_works: 'Young kids feel big feelings but often can\'t name them yet — which makes the feelings scarier and harder to manage. Having a face to point at gives them a way to say "I feel THIS" without needing the vocabulary. And once a feeling is named, it\'s already a little easier to handle.',
    safety_note: null,
    category: 'emotional',
  },
  {
    id: 'fallback-shadow-tracing',
    title: 'Shadow Detectives',
    description: 'Place toys in a sunny spot and trace around their shadows with chalk or crayons. Come back an hour later and the shadows have moved — genuine real-world magic that your child figured out on their own.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'focus',
    play_style_tags: 'building',
    routine_moment_tags: 'morning',
    time_minutes: 12,
    materials: 'A few small toys or figures (dinosaurs, dolls, and kitchen utensils all cast great shadows), chalk for outdoors or paper and crayons for a sunny windowsill, optional: a pencil to write the time next to each tracing',
    location: 'outdoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Find a sunny spot — outside on a path or inside near a bright window. Morning or late afternoon shadows are longest and most dramatic.',
      'Stand a toy up so it casts a clear shadow. Say: "Look — your dinosaur has a shadow friend! Let\'s draw around it so we can remember where it was."',
      'Trace around the shadow carefully with chalk or crayon. Write the time next to it (or draw a clock face if they\'re interested in that).',
      'Try 3-4 different toys. Ask: "Which toy makes the funniest shadow? What if you hold it at a different angle?"',
      'Leave the toys in place. Say: "I bet something interesting happens to the shadows later. Let\'s come back after lunch and check." Set an actual timer or alarm so you remember.',
      'Come back an hour later. The shadows have moved! Trace them again in a different colour. Say: "The shadow moved! But we didn\'t move the dinosaur... what do you think happened?"'
    ]),
    parent_script: '"Your dinosaur has a shadow! Can you trace around it with the chalk? Carefully, right around the edges... brilliant! Now here\'s the mystery — I think the shadow is going to MOVE. Let\'s come back after lunch and see."',
    fallback_if_refuses: 'Trace their own shadow on the pavement instead — have them strike a pose while you draw around it. Or just play with shadows: make hand puppets on the wall, see whose shadow is tallest, try to "step on" each other\'s shadows.',
    easier_version: 'Skip the tracing and just play with shadows — make shapes with your hands, chase each other\'s shadows, notice how they get longer near the end of the day.',
    harder_version: null,
    why_it_works: 'Tracing around a small shape takes careful hand control and sustained focus. And discovering that shadows move on their own plants a genuine "why does that happen?" question that they figured out through their own observation, not because someone told them.',
    safety_note: 'Hats and sun cream if you\'re outside for more than a few minutes. Move into the shade if anyone\'s getting pink.',
    category: 'cognitive',
  },
];

export const FALLBACK_ACTIVITIES_ES: Activity[] = [
  {
    id: 'fallback-colour-sorting',
    title: 'Misión de rescate del arcoíris',
    description: 'Tu peque se convierte en un héroe que rescata colores: junta objetos sueltos de la casa y los devuelve a su hogar del color que les toca. Calcetines, bloques, crayones, fruta… todo va a parar a los tazones.',
    age_min: 2,
    age_max: 4,
    goal_tags: 'independent_play',
    play_style_tags: 'building',
    routine_moment_tags: 'morning',
    time_minutes: 10,
    materials: '3 o 4 tazones o platos, un puñado de objetos coloridos de la casa (calcetines sueltos, bloques de duplo, crayones, cucharas de plástico, una banana, un tomate… lo que puedas agarrar en 30 segundos)',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Agarra 3 o 4 tazones y ponlos en fila en el piso. Coloca un objeto de color en cada tazón como pista inicial: un calcetín rojo en uno, un bloque azul en otro.',
      'Esparce 10 o 15 objetos coloridos por el piso, cerca. Di: "¡Ay, no, todas estas cositas se mezclaron! ¿Las puedes rescatar y devolverlas a su hogar del color correcto?"',
      'Deja que tu peque agarre los objetos y decida dónde van. Si pone algo en el tazón "equivocado", no pasa nada: deja que él haga las reglas.',
      'Cuando haya ordenado todo, vacíen los tazones juntos y di: "¡Uy, se escaparon otra vez!" A la mayoría de los niños les encanta volver a ordenar dos o tres veces.',
      'Si sigue entusiasmado, propón una regla nueva: "¿Y si esta vez ordenamos por grandes y chiquitos?"'
    ]),
    parent_script: '"¡Ay, no, todos estos colores se revolvieron! El calcetín rojo está perdido. ¿Puedes encontrar dónde vive? ¡En ese tazón de ahí! Ahora, ¿puedes rescatar todas las demás cositas y llevarlas a su hogar?"',
    fallback_if_refuses: 'Tranqui: pon los tazones en el piso y empieza a ordenar tú mismo. Narra lo que haces con voz juguetona: "Mmm, ¿dónde va este bloque azul?" La mayoría de los niños se acerca en menos de un minuto. Si no, deja los tazones afuera y deja que lo descubra solo más tarde.',
    easier_version: 'Usa solo dos tazones con dos colores muy distintos (rojo y azul). Elige objetos que sean claramente de un solo color para que no haya decisiones difíciles.',
    harder_version: null,
    why_it_works: 'Agrupar cosas por color es una de las primeras habilidades "matemáticas": así los niños empiezan a notar patrones y categorías. Además les permite trabajar de forma independiente y tomar sus propias decisiones sobre dónde va cada cosa, lo que les da confianza.',
    safety_note: 'Evita objetos chiquitos como canicas o monedas con menores de 3 años: usa solo cosas demasiado grandes para que quepan en la boca.',
    category: 'cognitive',
  },
  {
    id: 'fallback-story-dice',
    title: 'Cartas de "voltea y cuenta"',
    description: 'Tú y tu peque dibujan cositas chistosas en pedacitos de papel, los voltean boca abajo y se turnan para sacar uno y agregar la siguiente parte de un cuento disparatado. Mientras peores los dibujos, más risa da.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'speech',
    play_style_tags: 'stories',
    routine_moment_tags: 'anytime',
    time_minutes: 15,
    materials: 'Papel de reciclaje roto o cortado en cuadritos (la propaganda del correo sirve genial), crayones o marcadores, una superficie plana donde extenderlos',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Rompe o corta el papel en unos 8 o 10 cuadritos. No tienen que quedar perfectos: lo torcido tiene su encanto.',
      'Cada uno dibuja cositas rápidas: un sol, un perro, una banana, una nave espacial, un charco, una corona… lo que se te ocurra. Los monitos de palitos son perfectos.',
      'Voltea todas las cartas boca abajo y revuélvelas sobre la mesa.',
      'Tú sacas la primera carta, la volteas y empiezas el cuento: "Había una vez una banana muy gruñona que iba caminando por la calle…"',
      'Tu peque saca la siguiente carta y agrega una frase. Ayúdalo si se traba: "Y entonces la banana vio un… (¡voltea!) …¡una nave espacial! ¿Y qué pasó después?"',
      'Sigan hasta que alguien diga "¡Fin!"; mientras más disparatado el final, mejor.'
    ]),
    parent_script: '"Apuesto a que podemos hacer el cuento más chistoso de toda la casa. Yo empiezo, ¿listo? (Voltea una carta.) Había una vez un pingüino muy confundido que perdió sus zapatos. ¡Tu turno! Saca una carta y cuéntame qué pasa después."',
    fallback_if_refuses: 'Empieza a contar el cuento tú mismo con voz exagerada, haciendo pausas en los momentos emocionantes: "Y entonces el pingüino vio algo INCREÍBLE detrás de la puerta… me pregunto qué sería…" Deja una carta boca abajo frente a tu peque. La curiosidad casi siempre gana. Si no, disfruta simplemente contarle un cuento chistoso: igual es un gran rato de lenguaje.',
    easier_version: 'Recorta imágenes de una revista o de la propaganda del correo en vez de dibujar. O sáltate las cartas por completo y túrnense para ir agregando partes al cuento mientras van en el auto o durante la cena.',
    harder_version: null,
    why_it_works: 'Inventar cuentos ayuda a los niños a practicar el ordenar ideas, usar palabras nuevas y pensar en lo que viene después. El voltear las cartas agrega un elemento sorpresa que los mantiene enganchados más tiempo que contar cuentos sin estructura.',
    safety_note: null,
    category: 'language',
  },
  {
    id: 'fallback-freeze-dance',
    title: 'Fiesta de baile congelado',
    description: 'Sube la música y bailen como si nadie los viera; luego congélense cuando se detenga. La verdadera magia es que descarga un montón de energía y practica el detenerse a la señal, lo que después ayuda con las transiciones.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'calmer_transitions',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 10,
    materials: 'Un teléfono o parlante para la música (cualquier lista que le encante a tu peque) y suficiente espacio libre en el piso para bailar sin chocar con la mesa de centro',
    location: 'indoor',
    energy_level: 'high',
    steps_json: JSON.stringify([
      'Empuja los muebles para despejar una zona de baile. No tiene que ser grande: con unos pocos metros cuadrados basta.',
      'Pon algo movido que le guste a tu peque. Di: "Cuando suene la música, bailamos. Cuando se detiene, ¡CONGÉLATE como una estatua! Si te tambaleas, eliges la siguiente pose chistosa."',
      'Bailen juntos. Sé ridículo: agita los brazos, da vueltas, mueve las caderas. Mientras más payaso seas, más se entrega tu peque.',
      'Detén la música de repente. Mantén tu pose congelada y di "¡Estaaatua!" en un susurro dramático. Ríanse de las poses del otro.',
      'Después de 5 o 6 rondas, ve poniendo canciones más lentas. Di: "Ahora bailamos en cámara lenta… como astronautas en la luna…"',
      'Termina con una canción muy lenta y un balanceo suave. Esta es la parte astuta: le estás enseñando a calmarse.'
    ]),
    parent_script: '"¡Fiesta de baile! Cuando suene la música, muéstrame tus pasos más locos. Pero cuando se detiene… ¡CONGÉLATE! No muevas ni un músculo. ¿Listo? ¡Vamos!"',
    fallback_if_refuses: 'Empieza a bailar tú solo, lo más payaso posible. Casi ningún niño puede resistirse a unirse a un papá o una mamá que baila. Si aun así no quiere, deja que la música suene de fondo mientras hace lo suyo: hasta mover la cabeza al ritmo cuenta.',
    easier_version: 'Sáltate por completo la regla de congelarse. Solo bailen juntos. Eso ya es maravilloso.',
    harder_version: null,
    why_it_works: 'Detener el cuerpo a mitad de movimiento requiere autocontrol de verdad: la misma habilidad que ayuda a los niños a frenar antes de arrebatar un juguete o a calmarse cuando dices "espera". Envolverlo en una fiesta de baile hace que lo practiquen una y otra vez sin que se sienta como una lección.',
    safety_note: 'Revisa el piso por juguetes, zapatos o cualquier cosa resbaladiza antes de empezar. Los calcetines sobre piso de madera resbalan: los pies descalzos o los calcetines antideslizantes son más seguros.',
    category: 'physical',
  },
  {
    id: 'fallback-blanket-fort',
    title: 'La guarida secreta de lectura',
    description: 'Construyan juntos una cueva acogedora con mantas, métanse adentro con una linterna y una pila de libros favoritos, y lean en su propio mundito. Esta casi siempre termina siendo un pedido a la hora de dormir.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'connection',
    play_style_tags: 'stories',
    routine_moment_tags: 'evening',
    time_minutes: 20,
    materials: 'Una o dos mantas, cojines del sofá o sillas del comedor para la estructura, una linterna o lucecitas o un teléfono con la linterna encendida, 2 o 3 libros favoritos, una almohada para recostarse',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Coloca una manta sobre el espacio entre el sofá y una silla, o sobre una mesa. No tiene que ser una obra de arquitectura: que quede floja está bien.',
      'Deja que tu peque meta cojines y almohadas adentro. Di: "Tú eres el constructor: hazla todo lo acogedora que quieras."',
      'Enciende una linterna o lucecitas adentro. El cambio de luz es la magia: hace que un cuarto común se sienta completamente distinto.',
      'Métanse juntos. Deja que tu peque elija qué libro leer primero. Lee con voz más suave de lo normal: el espacio pequeño lo invita.',
      'Cuando terminen los libros, quédense recostados un ratito. Pregunta: "¿Qué fue lo mejor que pasó hoy?" La guarida hace que estas conversaciones salgan más fácil.',
      'Deja la guarida armada si puedes: lo más seguro es que tu peque vuelva a ella por su cuenta.'
    ]),
    parent_script: '"Vamos a construir una guarida secreta de lectura, solo para nosotros. Tú eliges los libros que pueden entrar y yo traigo la linterna. Nadie más conoce este lugar."',
    fallback_if_refuses: 'Deja que se concentre en construir la guarida: acomodar cojines y poner mantas es una actividad genial por sí sola. La lectura suele colarse una vez que la guarida se siente "lista". Si no, no pasa nada: construyó algo y tú estuviste ahí.',
    easier_version: 'Pon una sola manta sobre una mesa: guarida instantánea, sin nada de ingeniería. Tira una almohada debajo y listo.',
    harder_version: null,
    why_it_works: 'Los espacios chiquitos y cerrados se sienten seguros y especiales para los niños pequeños: es como tener su propio mundito. Leer juntos en ese espacio acogedor y tranquilo fortalece su conexión de una forma difícil de lograr en el sofá con la tele cerca.',
    safety_note: null,
    category: 'bonding',
  },
  {
    id: 'fallback-kitchen-band',
    title: 'Orquesta de ollas y cucharas',
    description: 'Asalten la alacena en busca de instrumentos: las ollas son tambores, un batidor sobre un colador es un güiro, arroz en un recipiente cerrado es una maraca. Túrnense para ser el director que controla fuerte, suave, rápido y lento.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'focus',
    play_style_tags: 'moving',
    routine_moment_tags: 'morning',
    time_minutes: 10,
    materials: 'Un par de ollas o cacerolas, cucharas de madera, un recipiente de plástico con un puñado de arroz cerrado adentro (maraca), una tapa de metal o una bandeja para horno (platillo), un batidor',
    location: 'indoor',
    energy_level: 'medium',
    steps_json: JSON.stringify([
      'Saca 3 o 4 "instrumentos" de la cocina y ponlos en el piso: una olla y una cuchara de madera (tambor), un recipiente cerrado con arroz (maraca), una bandeja para horno (platillo).',
      'Dale a tu peque una cuchara de madera. Deja que golpee todo durante un minuto para soltar las energías: esta parte es puro ruido, y está bien.',
      'Ahora presenta el juego del director: "Cuando levanto mi cuchara bien alto, tocas FUERTE. Cuando la bajo, tocas tan suave como un ratoncito."',
      'Practiquen fuerte y suave un par de veces, y luego agreguen rápido y lento. Exagera tus movimientos: a los niños les encanta el drama.',
      'Cambien de rol. Di: "¡Tu turno de ser el jefe de la banda! Yo tengo que hacer lo que tú digas." Sigue su ritmo con entusiasmo, aunque solo sea "FUERTE FUERTE FUERTE".',
      'Vayan calmándose dirigiendo una "canción de cuna": cada vez más lento y más suave, hasta que apenas estén dando golpecitos.'
    ]),
    parent_script: '"¡Vamos a armar una banda! Tú eres el baterista: aquí está tu baqueta. Cuando levante mi cuchara bien alto, toca tan FUERTE como puedas. Cuando la baje bien abajo, toca tan suave que solo un ratoncito pueda oír. ¿Listo?"',
    fallback_if_refuses: 'Siéntate en el piso y empieza a marcar un ritmo suave tú mismo. No lo invites: solo toca. Tararea. La mayoría de los niños agarra un instrumento en un par de minutos. Si no, deja los "instrumentos" afuera. Quizás vuelva a ellos más tarde.',
    easier_version: 'Sáltate por completo las reglas del director y solo toquen juntos. Inventen una canción chistosa sobre lo que van a comer al almuerzo.',
    harder_version: null,
    why_it_works: 'Observar a alguien e imitar lo que hace (tocar fuerte cuando da la señal de fuerte, parar cuando da la señal de parar) es atención y control de impulsos disfrazados. Los niños ni se dan cuenta de que están practicando porque se están divirtiendo demasiado haciendo ruido.',
    safety_note: 'Mantén fuera de su alcance los platos que se rompen y las tapas de vidrio. Solo objetos de madera y plástico.',
    category: 'sensory',
  },
  {
    id: 'fallback-treasure-hunt',
    title: 'Búsqueda del tesoro en el patio',
    description: 'Hagan juntos una lista rápida de tesoros: una hoja con puntas, algo liso, un palito chiquito, algo que huela interesante… y luego salgan afuera y deja que tu peque lidere la expedición.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'independent_play',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 15,
    materials: 'Un pedazo de papel y un crayón para la lista, una bolsa o recipiente para los tesoros (una bolsa de compras reutilizable sirve genial), zapatos que no te importe que se enloden',
    location: 'outdoor',
    energy_level: 'medium',
    steps_json: JSON.stringify([
      'Siéntense juntos y dibujen una lista rápida: una hoja, una piedra lisa, un palito, algo que huela rico y algo con texturas. Dibuja cositas al lado de cada uno para que tu peque pueda "leerla".',
      'Dale la bolsa y la lista. Di: "Tú eres el líder de la expedición. Yo soy tu ayudante: dime hacia dónde ir."',
      'Sigue su liderazgo afuera. Aguanta las ganas de señalar las cosas de inmediato: dale unos buenos 30 segundos para mirar antes de darle una pista.',
      'Cuando encuentre algo, táchenlo de la lista juntos. Hazle fiesta: "¡Una piña con texturas! ¡Qué gran hallazgo!"',
      'Cuando hayan tachado todo, lleven los tesoros a casa y acomódenlos en fila del más chiquito al más grande, o hagan un pequeño collage de naturaleza en un plato de cartón.',
      'Deja la colección en un lugar a la vista. Lo más seguro es que le cuente de su expedición a la primera persona que entre.'
    ]),
    parent_script: '"Vamos a una búsqueda del tesoro y TÚ eres el jefe del mapa. Lo primero de la lista: ¿puedes encontrar una hoja? Cualquier tipo de hoja. ¡Tú guías el camino y yo te sigo!"',
    fallback_if_refuses: 'Simplifícalo a "encuéntrame tres cosas interesantes": sin lista, sin reglas. O empieza a levantar cosas tú mismo y a pensar en voz alta sobre ellas: "Uy, esta piedra está tan lisa. Me pregunto si puedo encontrar una áspera…" Los niños suelen unirse cuando se siente como explorar y no como una tarea.',
    easier_version: 'Sáltate la lista. Solo lleva una bolsa y junten lo que a tu peque le parezca genial. Tres tesoros es un número perfecto para los más chiquitos.',
    harder_version: null,
    why_it_works: 'Ser el "líder" les da a los niños un sentido de propiedad e independencia. La lista agrega la estructura justa para mantenerlos enganchados sin convertir un paseo en una tarea. Y acomodar sus hallazgos después cuela, de paso, el ordenar y comparar tempranos.',
    safety_note: 'Quédate a una distancia de un brazo cerca de calles o agua. Recuérdale mirar primero con los ojos antes de levantar cualquier cosa con púas o desconocida. Deja en paz los jardines de otras personas.',
    category: 'outdoor',
  },
  {
    id: 'fallback-calm-down-jar',
    title: 'Frasco de la calma con brillantina',
    description: 'Hagan juntos un frasco brillante: agua tibia, un chorrito de pegamento y un montón de brillantina. Agítenlo cuando las emociones se hagan grandes y respiren juntos mientras ven la brillantina caer despacio hasta el fondo.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'calmer_transitions',
    play_style_tags: 'routine',
    routine_moment_tags: 'anytime',
    time_minutes: 15,
    materials: 'Un frasco transparente o botella de plástico con tapa que cierre bien (un frasco de mermelada limpio o una botella de agua vieja sirven), agua tibia, pegamento transparente o glicerina (un chorrito), brillantina o lentejuelas, cinta fuerte o pegamento extrafuerte para sellar la tapa',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Llena el frasco hasta unas tres cuartas partes con agua tibia. Deja que tu peque ayude a verter: un embudo o una jarra lo hace más fácil y con menos desorden.',
      'Echa un chorro de pegamento transparente (como una cucharada). Esto es lo que hace que la brillantina caiga despacio en vez de irse al fondo de golpe. Revuélvelo.',
      'Deja que tu peque agregue brillantina o lentejuelas con una cuchara. Mientras más, mejor: déjalo a sus anchas.',
      'Cierra bien la tapa y luego séllala con cinta fuerte o un anillo de pegamento extrafuerte para que no se pueda abrir. Espera a que el pegamento se seque.',
      'Agiten el frasco juntos y miren cómo gira la brillantina. Di: "¿Ves cómo todo da vueltas? A veces nuestras emociones son así, todas arremolinadas. Vamos a respirar y a verlas asentarse."',
      'Den tres respiraciones lentas juntos mientras la brillantina va cayendo. Di: "Para cuando la brillantina llegue al fondo, nuestros cuerpos también se sentirán más calmados."'
    ]),
    parent_script: '"Vamos a hacer algo brillante juntos. Y aquí viene lo genial: cuando te sientas todo burbujeante por dentro, como cuando te frustras o todo se siente demasiado, agitas este frasco y miras las chispitas. Para cuando lleguen al fondo, te sentirás un poco más calmado. ¡Vamos a probar!"',
    fallback_if_refuses: 'Conviértelo primero en un proyecto de manualidades: "Solo estamos haciendo algo brillante." Sáltate por completo la conversación sobre las emociones. Una vez que el frasco exista, lo agitará por diversión, y la parte de calmarse pasa sola. Siempre puedes hablar de las emociones otro día.',
    easier_version: 'Usa una bola de nieve ya hecha, o llena una botella transparente con agua y unas gotas de colorante de comida: agítala y miren cómo el color se arremolina y poco a poco se aclara.',
    harder_version: null,
    why_it_works: 'Ver algo moverse despacio mientras respiras le da a tu cuerpo la oportunidad de pasar del "modo alerta" al "modo calma". También funciona con los adultos: pruébalo. Tener un objeto físico al que recurrir cuando las emociones son grandes les da a los niños algo que hacer con las manos en vez de reaccionar de golpe.',
    safety_note: 'Sella bien la tapa: agua tibia más brillantina sobre la alfombra no le gusta a nadie. Supervisa a los más chiquitos durante el paso del pegamento extrafuerte.',
    category: 'emotional',
  },
  {
    id: 'fallback-block-tower',
    title: 'La torre más alta de la casa',
    description: 'Construyan juntos la torre más alta que puedan, un bloque a la vez, por turnos. El suspenso de "¿se va a caer?" los mantiene totalmente concentrados. Cuando se derrumbe (y se va a derrumbar), festejen y vuelvan a empezar.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'focus',
    play_style_tags: 'building',
    routine_moment_tags: 'anytime',
    time_minutes: 10,
    materials: 'Bloques de construcción, duplo o cualquier cosa apilable (cajas de zapatos, tubos de papel higiénico, latas de comida de la alacena… échale creatividad)',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Vacía todos tus bloques (o cosas apilables) en un montón en el centro del piso. Di: "Apuesto a que podemos construir una torre más alta que tu osito."',
      'Túrnense para colocar un bloque cada uno. Cuenten en voz alta juntos a medida que avanzan: "Uno… dos… tres…"',
      'Hazlo dramático. Susurra a medida que la torre crece: "Con cuidado… con cuidado…" Aguanta la respiración de forma teatral cuando se tambalee.',
      'Cuando se derrumbe, ¡festeja! "¡OCHO bloques! ¡Eso fue INCREÍBLE! ¿Le ganamos al ocho esta vez?"',
      'Después de unas cuantas rondas, deja que tu peque construya solo mientras tú cuentas y narras como comentarista deportivo: "¡Va por el bloque número DIEZ, amigos, una técnica increíble!"'
    ]),
    parent_script: '"A ver qué tan alta la podemos hacer. Tú pones uno, luego yo pongo uno. ¿Listo? Empieza tú: elige uno bien firme para la base."',
    fallback_if_refuses: 'Construye una torre tú mismo y deja que tu peque sea quien la derribe. Destruir es muy satisfactorio a esta edad, y una vez que haya tumbado unas cuantas, normalmente va a querer construir una para tumbarla. Eso cuenta.',
    easier_version: 'Construyan uno al lado del otro en vez de compartir una sola torre. Sin la presión de los turnos, y así puede copiar tu técnica.',
    harder_version: null,
    why_it_works: 'Esperar tu turno, aunque sean solo unos segundos, es práctica genuina de paciencia. Y el acto físico de apilar (alinear los bordes, equilibrar, ajustar) desarrolla el control de las manos y la conciencia espacial. El conteo cuela, de paso, un poco de sentido numérico temprano.',
    safety_note: null,
    category: 'cognitive',
  },
  {
    id: 'fallback-puppet-show',
    title: 'Teatro de títeres de calcetín',
    description: 'Asalten el cajón de calcetines sueltos, dibújenles caras y monten un show juntos. Los títeres dejan que los niños practiquen cosas sociales difíciles (compartir, pedir perdón, conocer a alguien nuevo) sin riesgos del mundo real.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'speech',
    play_style_tags: 'stories',
    routine_moment_tags: 'evening',
    time_minutes: 15,
    materials: 'Dos calcetines sueltos (mientras más viejos, mejor), un marcador o plumón para las caras y, si quieres: ojos saltones, botones, lana para el pelo, un sofá detrás del cual esconderse como "escenario"',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Ponte un calcetín en la mano y dibuja dos puntos para los ojos y una boca torcida. Di con voz chistosa: "¡Hola! Me llamo Profesor Calcetín. ¿Y TÚ quién eres?" Dale a tu peque el otro calcetín y un marcador.',
      'Deja que decore su títere como quiera. Ojos chuecos, tres bocas, una nariz garabateada: todo es perfecto.',
      'Empieza una escena sencilla con tu títere. Elige algo familiar: "El Profesor Calcetín va a la tienda. Necesita comprar bananas, ¡pero no las encuentra por ninguna parte! ¿Puede ayudar tu títere?"',
      'Deja que tu peque tome el control del cuento. Sigue su ritmo, aunque se vaya por las ramas por completo. Si se traba, haz que tu títere le haga una pregunta a su títere.',
      'Si está enganchado, escóndanse detrás del sofá como "escenario" y hagan una función para un público de peluches.',
      'Deja los títeres en un lugar a la vista: los títeres de calcetín tienen la costumbre de reaparecer en el desayuno de la mañana siguiente.'
    ]),
    parent_script: '"(Con voz agudita y chillona) ¡Hola! Soy el Profesor Calcetín y estoy un poco confundido. No me acuerdo dónde dejé mis zapatos, lo cual es gracioso porque ¡soy un calcetín! ¿Crees que tu títere me podría ayudar?"',
    fallback_if_refuses: 'Usa el títere para hablarle a tu peque en vez de hablarle directamente. Los niños que no quieren hablar contigo a veces conversan felices con un títere: se siente menos directo. El "Profesor Calcetín" puede preguntarle qué quiere de cena o qué pasó en la guardería.',
    easier_version: 'Sáltate la decoración: solo ponte un calcetín en la mano y haz que "hable". El títere más sencillo es solo tu mano abriéndose y cerrándose.',
    harder_version: null,
    why_it_works: 'Cuando un títere dice algo, no se siente que "cuente" igual que las palabras de verdad, así que los niños prueban frases nuevas, exploran situaciones y practican conversaciones con mucha menos vergüenza que cara a cara.',
    safety_note: null,
    category: 'language',
  },
  {
    id: 'fallback-obstacle-course',
    title: 'Carrera de obstáculos en la sala',
    description: 'Cojines como piedras para cruzar, un túnel de sillas para gatear, una línea de cinta para hacer equilibrio y una almohada para saltar al final. Cronometra sus vueltas y luego deja que la reconstruya como quiera.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'fewer_screens',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 15,
    materials: 'Cojines del sofá, sillas del comedor, cinta de papel o cinta de pintor (para una línea de equilibrio en el piso), una almohada como zona de aterrizaje para el salto, un cronómetro en tu teléfono',
    location: 'indoor',
    energy_level: 'high',
    steps_json: JSON.stringify([
      'Pon 4 o 5 cojines del sofá en un camino zigzagueante por el piso: son las piedras para cruzar sobre la "lava". Di: "Pase lo que pase, no toques el piso: ¡es lava!"',
      'Arma dos sillas con un espacio para gatear por en medio (el "túnel"). Si quieres, ponle una manta encima para más efecto.',
      'Pega una línea de cinta en el piso para una barra de equilibrio. Con unos dos metros basta.',
      'Pon una almohada al final como colchoneta para un salto de victoria.',
      'Recorre la carrera una vez tú mismo, narrando cada parte: "Piedras para cruzar, por el túnel, camina por la cuerda floja y… ¡SALTA!" Luego di: "Tu turno. Te estoy cronometrando: en sus marcas, listos, ¡YA!"',
      'Después de tres o cuatro vueltas, dale el poder: "Ahora TÚ diseñas la carrera para MÍ." Lo que sea que arme, hazlo con total compromiso.'
    ]),
    parent_script: '"OK, el trato es así. El piso es lava, eso es un túnel, eso es una cuerda floja y al final saltas a la colchoneta. Te estoy cronometrando en mi teléfono. ¿Listo? Tres… dos… uno… ¡YA!"',
    fallback_if_refuses: 'Arma la carrera y hazla tú mismo: cronométrate, resopla, lucha de forma dramática para pasar por el túnel. Luego di como sin querer: "Hice 14 segundos. Apuesto a que nadie podría ganarme." Aléjate. Espera.',
    easier_version: 'Solo los cojines para cruzar: sin cronómetro, sin gatear, nada más "no toques la lava" mientras cruzan el cuarto.',
    harder_version: null,
    why_it_works: 'Esto rasca la misma comezón que una pantalla: es novedoso, emocionante y tiene una meta clara. Pero además descarga energía física, desarrolla la coordinación y le da al niño una sensación de logro que dura más que el subidón de otro video de YouTube.',
    safety_note: 'Asegúrate de que las sillas no se puedan voltear. Aleja de la zona de aterrizaje cualquier cosa filosa o dura. Los pies descalzos agarran mejor que los calcetines.',
    category: 'physical',
  },
  {
    id: 'fallback-bedtime-yoga',
    title: 'Yoga de animalitos somnolientos',
    description: 'Cinco estiramientos suaves de animales que llevan a tu peque de inquieto a relajado. Gato, mariposa, flamenco, oso somnoliento y erizo enroscado: cada uno un poquito más calmado que el anterior.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'easier_bedtime',
    play_style_tags: 'routine',
    routine_moment_tags: 'bedtime',
    time_minutes: 8,
    materials: 'Nada: solo un poco de espacio en el piso junto a su cama y quizás una manta para recostarse',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Empiecen de pie. Di: "Vamos a ser cinco animalitos somnolientos antes de dormir. Primero, un gato que acaba de despertar de una siesta." Ponte en cuatro patas, arquea la espalda hacia arriba como un gato que se estira, y luego húndela. Háganlo tres veces, despacio.',
      'Siéntense en el piso juntos. "Ahora somos mariposas secando nuestras alas al sol." Pies juntos, rodillas hacia afuera, mueve suavemente las rodillas hacia arriba y hacia abajo. Inhala cuando las rodillas suben, exhala cuando bajan.',
      'Párate en una pierna. "¡Flamenco! ¿Puedes hacer equilibrio sin caerte al estanque?" Abre los brazos bien anchos. Tambalearse y reírse es justo de lo que se trata.',
      '"Ahora somos un oso cansado que vuelve a su cueva." Párate y luego dóblate despacio hacia adelante, dejando que los brazos cuelguen pesados como las patas de un oso. Balancéate suave de un lado a otro.',
      '"El último. Somos erizos enroscándonos para el invierno." Recuéstate y enróscate en la bolita más chiquita y apretada que puedas. Susurra: "Erizo chiquitito… tan acurrucadito… con tanto sueño…"',
      'Desenróscate despacio. Recuéstate plano y den tres respiraciones grandes juntos. Si ya está en la cama, arrópalo y di: "Hasta el erizo está dormido."'
    ]),
    parent_script: '"Hora del yoga de animalitos somnolientos. Vamos a ser cinco animales, y cada uno tiene un poquito más de sueño que el anterior. Primero, muéstrame tu mejor estiramiento de gato. Estírate grande… bieeen grande… ahhh."',
    fallback_if_refuses: 'Haz las poses tú mismo junto a su cama, narrando con voz suave y lenta: "Soy un gato estirándome… ahora soy una mariposa…" No le pidas que se una. El movimiento suave y la voz tranquila suelen atraerlo. Si solo mira desde la cama, está bien: igual se está calmando.',
    easier_version: 'Hagan solo las últimas dos poses recostados en la cama: oso somnoliento (estirar los brazos hacia arriba y luego dejarlos caer) y erizo enroscado (enroscarse en bolita). Dos minutos y listo.',
    harder_version: null,
    why_it_works: 'Los movimientos lentos y predecibles con respiración profunda le dicen al cuerpo que es seguro relajarse. Pasar por una secuencia, sobre todo una que se va calmando poco a poco, es mucho más efectivo para calmarse que solo decir "cálmate, por favor".',
    safety_note: null,
    category: 'routine',
  },
  {
    id: 'fallback-magic-drawing',
    title: 'Pintura de dibujo secreto',
    description: 'Dibuja una imagen invisible con un crayón blanco sobre papel blanco, luego dale a tu peque las acuarelas y observa su cara cuando la imagen escondida aparece como por magia bajo la pintura.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'independent_play',
    play_style_tags: 'building',
    routine_moment_tags: 'morning',
    time_minutes: 12,
    materials: 'Papel blanco, un crayón blanco (o un cabito de vela blanca, que funciona aún mejor), acuarelas o colorante de comida diluido en agua, un pincel grueso, un vaso con agua, algo para proteger la mesa (periódico, una bolsa de basura, una toalla vieja)',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Mientras tu peque no está mirando (o está entretenido con otra cosa un momento), presiona fuerte con un crayón blanco sobre papel blanco y dibuja algo que vaya a reconocer: una estrella, la inicial de su nombre, una carita de gato, un corazón.',
      'Saca las pinturas, un pincel y el vaso con agua. Pon el papel frente a tu peque y di: "Hay un dibujo secreto escondido en este papel. La única forma de encontrarlo es pintar encima."',
      'Deja que pinte como quiera. A medida que el color pasa sobre la cera, la imagen escondida aparece. Mira su cara: esta parte es genuinamente encantadora.',
      'Di: "¡La encontraste! ¡Era una estrella! ¿Quieres hacerme una a mí ahora?" Dale el crayón blanco y una hoja nueva.',
      'Deja que dibuje su propio dibujo secreto (va a presionar bien fuerte, lo cual es genial para la fuerza de la mano), y luego tú pintas encima para "encontrarlo".',
      'Sigan todo el tiempo que esté interesado. Esta actividad tiene una capacidad de entretener sorprendentemente larga.'
    ]),
    parent_script: '"Escondí un dibujo secreto en este papel. Todavía no lo puedes ver, pero si pintas encima, va a aparecer como por magia. ¡Agarra el pincel y descubramos qué es!"',
    fallback_if_refuses: 'Sáltate la parte del dibujo secreto y solo saca las acuarelas para pintar libremente. A casi ningún niño se le resiste un set de pintura abierto. Siempre puedes probar el truco del dibujo escondido otro día, cuando sea el momento adecuado.',
    easier_version: 'Tú haces todo el dibujo; tu peque solo pinta para revelarlo. Para los más chiquitos, usa un cabito grueso de vela en vez de un crayón: es más fácil de agarrar y deja una mejor reserva de cera.',
    harder_version: null,
    why_it_works: 'La sorpresa de ver aparecer algo invisible mantiene la atención mucho más tiempo que pintar normal. Y presionar fuerte con el crayón y luego controlar un pincel mojado a lo largo de la hoja desarrolla la fuerza y el control de la mano que va a necesitar para escribir.',
    safety_note: 'Cubre la mesa y el piso cercano: las acuarelas son lavables, pero la pintura entusiasta de un peque llega más lejos de lo que uno espera. Súbele las mangas o usa una camisa vieja como bata.',
    category: 'creative',
  },
  {
    id: 'fallback-puddle-splash',
    title: 'Cocina de charcos',
    description: 'Salgan afuera con vasos, un embudo y una cuchara. Tu peque se convierte en "chef": revuelve sopa de charco, vierte de un recipiente a otro, prueba qué flota y qué se hunde. Desordenado, absorbente y sorprendentemente duradero.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'independent_play',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 15,
    materials: 'Botas de lluvia y ropa que no te importe que se moje, 2 o 3 vasos o recipientes de distintos tamaños, un embudo si tienes, una cuchara para revolver, unas cuantas cositas para probar (hoja, piedra, palito, tapa de botella, piña)',
    location: 'outdoor',
    energy_level: 'medium',
    steps_json: JSON.stringify([
      'Equípense: botas de lluvia, ropa vieja, chamarra si hace frío. Acepta de antemano que se va a mojar. Di: "Hoy vamos a ser chefs de charcos. ¡Gorro de chef puesto!"',
      'Encuentren un charco, o llena una palangana con agua afuera. Pon los vasos, el embudo y la cuchara cerca.',
      'Empieza el juego: "Primero, tenemos que hacer sopa de charco. ¿La puedes revolver con la cuchara? Ahora sirve un poco en este vaso. ¿Ya está lleno?"',
      'Introduce el flotar y el hundirse: "Reto del chef: ¿qué ingredientes flotan en nuestra sopa?" Echa una hoja (¡flota!) y luego una piedra (¡se hunde!). Deja que pruebe otras cositas.',
      'Da un paso atrás. Una vez que esté vertiendo de un recipiente a otro y echando cosas, la mayoría de los niños juega feliz 10 o 15 minutos sin necesidad de que lo dirijas.',
      'Cuando sea hora de entrar, da un aviso de dos minutos: "Dos vertidos más y luego entramos por calcetines calientitos." Cumple con calma.'
    ]),
    parent_script: '"¡Hoy somos chefs de charcos! Primera tarea: sirve un poco de agua en este vaso. ¿Está lleno? Ahora viértela en el vaso grande. ¿Se llena? Hagamos sopa: ¿qué le ponemos? ¿Qué tal esta hoja?"',
    fallback_if_refuses: 'Sáltate por completo lo estructurado. Solo pisoteen el charco juntos. Una vez que ya esté afuera y ya esté mojado, los vasos y el verter suelen pasar solos. La meta es sacarlo al aire libre: todo lo demás viene después.',
    easier_version: 'Solo chapotear y pisotear: sin vasos, sin verter, sin ciencia. Con eso basta para los más chiquitos y para los días de lluvia en que solo necesitas que descargue energías.',
    harder_version: null,
    why_it_works: 'El agua es naturalmente hipnótica para los niños pequeños. Verter de un recipiente a otro es una de las mejores formas en que aprenden sobre "más y menos", "lleno y vacío" y "pesado y liviano": conceptos matemáticos fundamentales que se quedan mejor con el juego práctico que con tarjetas.',
    safety_note: 'Quédate a una distancia de un brazo cada vez que haya agua de por medio. Cámbialo a ropa seca rápido después para que no se enfríe.',
    category: 'outdoor',
  },
  {
    id: 'fallback-feelings-faces',
    title: 'Galería de caras de emociones',
    description: 'Dibujen círculos grandes y vacíos en un papel y conviértanlos juntos en caras: feliz, gruñón, sorprendido, chistoso, somnoliento. Luego péguenlas en el refri para que tu peque pueda señalar cómo se siente cuando las palabras no alcanzan.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'calmer_transitions',
    play_style_tags: 'building',
    routine_moment_tags: 'anytime',
    time_minutes: 10,
    materials: 'Papel (con una hoja basta), crayones o marcadores, cinta o un imán para pegarlas en el refri',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Dibuja 5 o 6 círculos grandes y vacíos en una hoja de papel. (Si te sientes con ganas, recórtalos.) Di: "Vamos a hacer una galería de emociones para el refri."',
      'Empieza con una fácil: "¿Puedes dibujar una cara feliz? ¿Cómo se ven los ojos felices? ¿Y la boca?" Dibuja la tuya al lado: no tiene que quedar bien.',
      'Pasen a otras emociones: gruñón (cejas hacia abajo, boca como zigzag), sorprendido (boca grande y redonda, ojos bien abiertos), chistoso (sacando la lengua), somnoliento (ojos caídos, boca bostezando).',
      'Después de cada una, pongan la cara juntos. "¡Muéstrame tu cara de gruñón! Grrrr. ¡Ahora muéstrame tu cara de sorpresa! ¡OH!" Esta parte normalmente da mucha risa.',
      'Pégalas en el refri a la altura de los ojos de tu peque. Di: "Ahora, cada vez que sientas algo grande, puedes señalar la cara que combina. Aunque no encuentres las palabras, me lo puedes mostrar."',
      'Durante los días siguientes, úsalas tú mismo: "Me siento un poco gruñón ahora mismo… mira, esa cara de ahí. Pero creo que un cafecito me va a ayudar." Modelar esto es la parte más poderosa.'
    ]),
    parent_script: '"Vamos a dibujar unas caras de emociones para el refri. Tú sabes cómo se ve feliz… ¿la puedes dibujar? ¡Sonrisa grande! ¿Y ahora qué tal una cara de gruñón? Muéstramela primero con TU cara… ¡oh, esa es una muy buena cara de gruñón!"',
    fallback_if_refuses: 'Dibuja tú las caras y deja que tu peque solo las coloree, les ponga calcomanías o haga un círculo en la que combine con cómo se siente ahora mismo. Hasta señalar una cara ya dibujada es un logro: la meta es darle una forma de comunicar emociones, no crear arte.',
    easier_version: 'Dibuja tú las caras e imprímelas o recórtalas. Tu peque solo necesita señalar una. También puedes usar calcomanías de emojis si tienes.',
    harder_version: null,
    why_it_works: 'Los niños pequeños sienten emociones grandes, pero muchas veces todavía no saben nombrarlas, lo que hace que las emociones den más miedo y sean más difíciles de manejar. Tener una cara que señalar les da una forma de decir "siento ESTO" sin necesitar el vocabulario. Y una vez que una emoción tiene nombre, ya es un poquito más fácil de manejar.',
    safety_note: null,
    category: 'emotional',
  },
  {
    id: 'fallback-shadow-tracing',
    title: 'Detectives de sombras',
    description: 'Pon juguetes en un lugar soleado y traza el contorno de sus sombras con tiza o crayones. Vuelvan una hora después y las sombras se habrán movido: magia genuina del mundo real que tu peque descubrió por su cuenta.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'focus',
    play_style_tags: 'building',
    routine_moment_tags: 'morning',
    time_minutes: 12,
    materials: 'Unos cuantos juguetes o figuras chiquitos (los dinosaurios, las muñecas y los utensilios de cocina hacen sombras geniales), tiza para afuera o papel y crayones para una ventana soleada y, si quieres: un lápiz para escribir la hora junto a cada trazo',
    location: 'outdoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Encuentren un lugar soleado: afuera en un sendero o adentro cerca de una ventana luminosa. Las sombras de la mañana o de la tarde son las más largas y dramáticas.',
      'Para un juguete de pie para que haga una sombra clara. Di: "Mira, ¡tu dinosaurio tiene un amigo sombra! Vamos a dibujar a su alrededor para acordarnos de dónde estaba."',
      'Traza con cuidado el contorno de la sombra con tiza o crayón. Escribe la hora al lado (o dibuja la cara de un reloj si eso le interesa).',
      'Prueben 3 o 4 juguetes distintos. Pregunta: "¿Cuál juguete hace la sombra más chistosa? ¿Y si lo sostienes en otro ángulo?"',
      'Dejen los juguetes en su lugar. Di: "Apuesto a que algo interesante les pasa a las sombras más tarde. Volvamos después del almuerzo a revisar." Pon un cronómetro o una alarma de verdad para que te acuerdes.',
      'Vuelvan una hora después. ¡Las sombras se movieron! Trácenlas de nuevo en otro color. Di: "¡La sombra se movió! Pero no movimos el dinosaurio… ¿qué crees que pasó?"'
    ]),
    parent_script: '"¡Tu dinosaurio tiene una sombra! ¿La puedes trazar con la tiza? Con cuidado, justo por las orillas… ¡genial! Ahora viene el misterio: creo que la sombra se va a MOVER. Volvamos después del almuerzo a ver."',
    fallback_if_refuses: 'Traza la propia sombra de tu peque en la vereda: que haga una pose mientras dibujas a su alrededor. O solo jueguen con las sombras: hagan títeres de mano en la pared, vean de quién es la sombra más alta, intenten "pisar" la sombra del otro.',
    easier_version: 'Sáltate el trazo y solo jueguen con las sombras: hagan formas con las manos, persigan la sombra del otro, fíjense en cómo se alargan al final del día.',
    harder_version: null,
    why_it_works: 'Trazar el contorno de una forma chiquita requiere control fino de la mano y concentración sostenida. Y descubrir que las sombras se mueven solas siembra una pregunta genuina de "¿por qué pasa eso?" que tu peque resolvió a través de su propia observación, no porque alguien se lo contó.',
    safety_note: 'Gorros y protector solar si están afuera más de unos minutos. Pásense a la sombra si alguien se está poniendo rojo.',
    category: 'cognitive',
  },
];

/** Back-compat: the generate route imports `FALLBACK_ACTIVITIES`. */
export const FALLBACK_ACTIVITIES = FALLBACK_ACTIVITIES_EN;

export function getFallbackActivities(locale: Locale): Activity[] {
  return locale === 'es' ? FALLBACK_ACTIVITIES_ES : FALLBACK_ACTIVITIES_EN;
}
