import type { Activity } from './plan-generator';

export const FALLBACK_ACTIVITIES: Activity[] = [
  {
    id: 'fallback-colour-sorting',
    title: 'Rainbow Rescue Mission',
    description: 'Your little one becomes a colour rescue hero, gathering mismatched household items and returning them to their matching colour homes. Socks, blocks, crayons, fruit — anything goes into the bowls.',
    age_min: 2,
    age_max: 4,
    goal_tags: 'independent_play',
    play_style_tags: 'building',
    routine_moment_tags: 'morning',
    time_minutes: 10,
    materials: '3-4 bowls or plates, a handful of colourful household items (odd socks, duplo bricks, crayons, plastic spoons, a banana, a tomato — whatever you can grab in 30 seconds)',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Grab 3-4 bowls and set them in a line on the floor. Put one coloured item in each bowl as a starter — a red sock in one, a blue block in another.',
      'Scatter 10-15 colourful items on the floor nearby. Say: "Oh no, all these things got mixed up! Can you rescue them and put them back in the right colour home?"',
      'Let your child pick up items and decide where they go. If they put something in the "wrong" bowl, that\'s fine — let them make the rules.',
      'When they\'ve sorted everything, tip the bowls out together and say: "Uh oh, they escaped again!" Most kids will happily re-sort two or three times.',
      'If they\'re still into it, suggest a new rule: "What if we sort by big and small this time?"'
    ]),
    parent_script: '"Oh no, all these colours got jumbled up! The red sock is lost — can you find where it lives? That bowl right there! Now can you rescue all the other things and get them home?"',
    fallback_if_refuses: 'No worries — just set the bowls on the floor and start sorting yourself. Narrate what you\'re doing in a playful voice: "Hmm, where does this blue block go?" Most kids wander over within a minute. If not, leave the bowls out and let them discover it on their own later.',
    easier_version: 'Use just two bowls with two very different colours (red and blue). Pick items that are clearly one colour so there\'s no tricky decisions.',
    harder_version: null,
    why_it_works: 'Grouping things by colour is one of the earliest "maths" skills — it\'s how kids start to notice patterns and categories. It also lets them work independently, making their own decisions about where things go, which builds confidence.',
    safety_note: 'Skip small items like marbles or coins for under-3s — stick to things too big to fit in a mouth.',
    category: 'cognitive',
  },
  {
    id: 'fallback-story-dice',
    title: 'Flip & Tell Story Cards',
    description: 'You and your child draw silly pictures on scraps of paper, flip them face-down, and take turns picking one to add the next bit of a ridiculous story. The worse the drawings, the funnier it gets.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'speech',
    play_style_tags: 'stories',
    routine_moment_tags: 'anytime',
    time_minutes: 15,
    materials: 'Scrap paper torn or cut into squares (junk mail works great), crayons or markers, a flat surface to spread them on',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Tear or cut paper into roughly 8-10 squares. They don\'t need to be neat — wobbly is charming.',
      'Each of you draws quick pictures on them: a sun, a dog, a banana, a spaceship, a puddle, a crown — whatever pops into your head. Stick figures are perfect.',
      'Flip all the cards face-down and jumble them up on the table.',
      'You pick the first card, flip it, and start the story: "Once upon a time, a very grumpy banana was walking down the road..."',
      'Your child picks the next card and adds a sentence. Help them along if they get stuck: "And then the banana saw a... (flip!) ...a spaceship! What happened next?"',
      'Keep going until someone declares "The End!" — the sillier the ending, the better.'
    ]),
    parent_script: '"I bet we can make the silliest story in the whole house. I\'ll go first — ready? (Flip a card.) Once upon a time, there was a very confused penguin who lost his shoes. Your turn — pick a card and tell me what happens next!"',
    fallback_if_refuses: 'Start telling the story yourself in an exaggerated voice, pausing at exciting moments: "And then the penguin saw something AMAZING behind the door... I wonder what it was..." Leave a card face-down in front of them. Curiosity usually wins. If not, just enjoy telling them a silly story — that\'s still great language time.',
    easier_version: 'Cut pictures from a magazine or junk mail instead of drawing. Or skip the cards entirely and just take turns adding to a story while you\'re in the car or at dinner.',
    harder_version: null,
    why_it_works: 'Making up stories helps kids practise putting ideas in order, using new words, and thinking about what comes next. The card-flipping adds a surprise element that keeps them engaged longer than open-ended storytelling.',
    safety_note: null,
    category: 'language',
  },
  {
    id: 'fallback-freeze-dance',
    title: 'Freeze Dance Party',
    description: 'Crank up some music and dance like nobody\'s watching — then freeze when it stops. The real magic is that it burns off a huge amount of energy and practises stopping on cue, which helps with transitions later.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'calmer_transitions',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 10,
    materials: 'A phone or speaker for music (any playlist your kid loves), enough clear floor space to dance without crashing into the coffee table',
    location: 'indoor',
    energy_level: 'high',
    steps_json: JSON.stringify([
      'Push furniture back to clear a dance zone. Doesn\'t need to be big — a few square metres is plenty.',
      'Put on something upbeat your child likes. Say: "When the music plays, we dance. When it stops — FREEZE like a statue! If you wobble, you pick the next silly pose."',
      'Dance together. Be ridiculous — flap your arms, spin in circles, wiggle your hips. The sillier you are, the more they commit.',
      'Pause the music suddenly. Hold your freeze and say "Staaatue!" in a dramatic whisper. Giggle at each other\'s poses.',
      'After 5-6 rounds, gradually pick slower songs. Say: "Now we\'re dancing in slow motion... like astronauts on the moon..."',
      'End with a very slow song and gentle swaying. This is the sneaky part — you\'re teaching them to wind down.'
    ]),
    parent_script: '"Dance party! When the music plays, show me your wildest moves. But when it stops — FREEZE! Don\'t move a muscle. Ready? Here we go!"',
    fallback_if_refuses: 'Start dancing by yourself, being as silly as possible. Most kids physically cannot resist joining a dancing parent. If they still don\'t want to, just let the music play in the background while they do their own thing — even bobbing their head counts.',
    easier_version: 'Skip the freeze rule entirely. Just dance together. That\'s still wonderful.',
    harder_version: null,
    why_it_works: 'Stopping your body mid-movement takes real self-control — the same skill that helps kids pause before grabbing a toy or calm down when you say "wait." Wrapping it in a dance party means they practise it over and over without it feeling like a lesson.',
    safety_note: 'Check the floor for toys, shoes, or anything slippery before you start. Socks on hardwood can be slippy — bare feet or grippy socks are safer.',
    category: 'physical',
  },
  {
    id: 'fallback-blanket-fort',
    title: 'Secret Reading Den',
    description: 'Build a cosy blanket cave together, crawl inside with a torch and a pile of favourite books, and read in your own little world. This one almost always becomes a bedtime request.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'connection',
    play_style_tags: 'stories',
    routine_moment_tags: 'evening',
    time_minutes: 20,
    materials: 'A blanket or two, sofa cushions or dining chairs for structure, a torch or fairy lights or a phone with the flashlight on, 2-3 favourite books, a pillow to lie on',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Drape a blanket over the gap between a sofa and a chair, or over a table. It doesn\'t need to be architectural — saggy is fine.',
      'Let your child stuff cushions and pillows inside. Say: "You\'re the builder — make it as cosy as you want."',
      'Switch on a torch or fairy lights inside. The change in lighting is the magic — it makes an ordinary room feel completely different.',
      'Crawl in together. Let your child pick which book to read first. Read in a softer voice than usual — the small space invites it.',
      'When you finish the books, just lie there for a minute. Ask: "What\'s the best thing that happened today?" The den makes these conversations easier.',
      'Leave the fort up if you can — they\'ll probably go back to it on their own.'
    ]),
    parent_script: '"Let\'s build a secret reading den — just for us. You pick the books that are allowed inside and I\'ll get the torch. Nobody else knows about this place."',
    fallback_if_refuses: 'Let them focus on building the fort — arranging cushions and draping blankets is a great activity all on its own. The reading often sneaks in once the fort feels "ready." If it doesn\'t, that\'s fine — they built something, and you were there.',
    easier_version: 'Drape one blanket over a table — instant den, no engineering required. Toss a pillow underneath and you\'re done.',
    harder_version: null,
    why_it_works: 'Small enclosed spaces feel safe and special to young kids — it\'s like having their own little world. Reading together in that cosy, quiet space strengthens your connection in a way that\'s hard to replicate on the sofa with the TV nearby.',
    safety_note: null,
    category: 'bonding',
  },
  {
    id: 'fallback-kitchen-band',
    title: 'Pots & Spoons Orchestra',
    description: 'Raid the kitchen cupboard for instruments — pots become drums, a whisk on a colander is a güiro, rice in a sealed container is a shaker. Take turns being the conductor who controls loud, soft, fast, and slow.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'focus',
    play_style_tags: 'moving',
    routine_moment_tags: 'morning',
    time_minutes: 10,
    materials: 'A couple of pots or saucepans, wooden spoons, a plastic container with a handful of rice sealed inside (shaker), a metal lid or baking tray (cymbal), a whisk',
    location: 'indoor',
    energy_level: 'medium',
    steps_json: JSON.stringify([
      'Pull out 3-4 "instruments" from the kitchen and set them on the floor: a pot and wooden spoon (drum), a sealed container with rice (shaker), a baking tray (cymbal).',
      'Give your child a wooden spoon. Let them bang on everything for a minute to get the wiggles out — this part is pure noise, and that\'s OK.',
      'Now introduce the conductor game: "When I hold my spoon up high, play LOUD. When I bring it down low, play as quietly as a mouse."',
      'Practise loud and soft a few times, then add fast and slow. Exaggerate your movements — kids love the drama.',
      'Switch roles. Say: "Your turn to be the boss of the band! I have to do whatever you say." Follow their lead enthusiastically, even when it\'s just "LOUD LOUD LOUD."',
      'Wind down by conducting a "lullaby" — get slower and softer until you\'re barely tapping.'
    ]),
    parent_script: '"We\'re starting a band! You\'re the drummer — here\'s your drumstick. When I hold my spoon way up high, play as LOUD as you can. When I bring it way down low, play so quiet that only a mouse could hear. Ready?"',
    fallback_if_refuses: 'Sit on the floor and start tapping out a gentle rhythm yourself. Don\'t invite them — just play. Hum along. Most kids pick up an instrument within a couple of minutes. If they don\'t, leave the "instruments" out. They might come back to them later.',
    easier_version: 'Skip the conductor rules entirely and just bang along together. Make up a silly song about what you\'re having for lunch.',
    harder_version: null,
    why_it_works: 'Watching someone and matching what they do — play loud when they signal loud, stop when they signal stop — is attention and impulse control in disguise. Kids don\'t notice they\'re practising because they\'re having too much fun being noisy.',
    safety_note: 'Keep breakable dishes and glass lids out of reach. Wooden and plastic items only.',
    category: 'sensory',
  },
  {
    id: 'fallback-treasure-hunt',
    title: 'Backyard Treasure Hunt',
    description: 'Make a quick treasure checklist together — a pointy leaf, something smooth, a tiny stick, anything that smells interesting — then head outside and let your child lead the expedition.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'independent_play',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 15,
    materials: 'A scrap of paper and a crayon for the checklist, a bag or container for treasures (a reusable shopping bag works great), shoes you don\'t mind getting muddy',
    location: 'outdoor',
    energy_level: 'medium',
    steps_json: JSON.stringify([
      'Sit down together and draw a quick checklist: a leaf, a smooth stone, a stick, something that smells nice, and something bumpy. Draw little pictures next to each one so your child can "read" it.',
      'Give them the bag and the list. Say: "You\'re the expedition leader. I\'m your assistant — tell me where to go."',
      'Follow their lead outside. Resist the urge to point things out right away — give them a good 30 seconds to look before you offer a hint.',
      'When they find something, tick it off the list together. Make a fuss: "A bumpy pinecone — brilliant find!"',
      'Once everything\'s ticked off, bring the treasures home and arrange them in a line from smallest to biggest, or make a little nature collage on a paper plate.',
      'Leave the collection somewhere visible. They\'ll probably tell the next person who walks in about their expedition.'
    ]),
    parent_script: '"We\'re going on a treasure hunt and YOU\'re the boss of the map. First on the list — can you find a leaf? Any kind of leaf. You lead the way and I\'ll follow!"',
    fallback_if_refuses: 'Simplify it to "find me three interesting things" — no checklist, no rules. Or start picking things up yourself and wondering aloud about them: "Ooh, this rock is so smooth. I wonder if I can find a rough one..." Kids often join in when it feels like exploring, not a task.',
    easier_version: 'Skip the checklist. Just bring a bag and collect anything they think is cool. Three treasures is a perfect number for younger kids.',
    harder_version: null,
    why_it_works: 'Being the "leader" gives kids a sense of ownership and independence. The checklist adds just enough structure to keep them engaged without turning a walk into a chore. And arranging their finds afterwards sneaks in early sorting and comparing.',
    safety_note: 'Stay within arm\'s reach near roads or water. Remind them to look with their eyes first before picking up anything spiky or unfamiliar. Leave other people\'s gardens alone.',
    category: 'outdoor',
  },
  {
    id: 'fallback-calm-down-jar',
    title: 'Calm-Down Glitter Jar',
    description: 'Make a sparkly jar together — warm water, a squeeze of glue, and a heap of glitter. Shake it up when feelings get big, and breathe together as you watch the glitter slowly drift to the bottom.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'calmer_transitions',
    play_style_tags: 'routine',
    routine_moment_tags: 'anytime',
    time_minutes: 15,
    materials: 'A clear jar or plastic bottle with a tight lid (a clean jam jar or old water bottle works), warm water, clear glue or glycerine (a small squeeze), glitter or sequins, strong tape or superglue to seal the lid',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Fill the jar about three-quarters full with warm water. Let your child help pour — a funnel or jug makes this easier and less messy.',
      'Squeeze in a blob of clear glue (about a tablespoon). This is what makes the glitter fall slowly instead of just dropping. Stir it in.',
      'Let your child spoon in glitter or sequins. More is more — let them go for it.',
      'Screw the lid on tight, then seal it with strong tape or a ring of superglue so it can\'t be opened. Wait for the glue to dry.',
      'Shake the jar together and watch the glitter swirl. Say: "See how everything\'s spinning around? Sometimes our feelings are like that — all swirly. Let\'s breathe and watch it settle."',
      'Take three slow breaths together while the glitter drifts down. Say: "By the time the glitter reaches the bottom, our bodies will feel calmer too."'
    ]),
    parent_script: '"Let\'s make something sparkly together. And here\'s the cool part — when you feel all fizzy inside, like when you\'re frustrated or everything feels too much, you shake this jar and watch the sparkles. By the time they reach the bottom, you\'ll feel a bit calmer. Let\'s try it!"',
    fallback_if_refuses: 'Make it a craft project first — "We\'re just making something sparkly." Skip the feelings conversation entirely. Once the jar exists, they\'ll shake it for fun, and the calming part happens on its own. You can always talk about feelings another day.',
    easier_version: 'Use a pre-made snow globe, or fill a clear bottle with water and a few drops of food colouring — shake it and watch the colour swirl and slowly clear.',
    harder_version: null,
    why_it_works: 'Watching something move slowly while you breathe gives your body a chance to switch from "alert mode" to "calm mode." It works for grown-ups too — try it. Having a physical object to reach for when feelings are big gives kids something to do with their hands instead of lashing out.',
    safety_note: 'Seal the lid properly — warm water plus glitter on the carpet is nobody\'s idea of a good time. Supervise younger kids around the superglue step.',
    category: 'emotional',
  },
  {
    id: 'fallback-block-tower',
    title: 'Tallest Tower in the House',
    description: 'Build the tallest tower you can together, one block at a time, taking turns. The suspense of "will it fall?" keeps them completely focused. When it crashes — and it will — cheer and start again.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'focus',
    play_style_tags: 'building',
    routine_moment_tags: 'anytime',
    time_minutes: 10,
    materials: 'Building blocks, duplo, or anything stackable (shoeboxes, toilet roll tubes, food tins from the cupboard — get creative)',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Tip all your blocks (or stackable items) into a pile in the middle of the floor. Say: "I bet we can build a tower taller than your teddy bear."',
      'Take turns placing one block each. Count out loud together as you go: "One... two... three..."',
      'Make it dramatic. Whisper as the tower gets tall: "Careful... careful..." Hold your breath theatrically when it wobbles.',
      'When it crashes, cheer! "EIGHT blocks! That was AMAZING! Can we beat eight this time?"',
      'After a few rounds, let your child build solo while you count and commentate like a sports announcer: "She\'s going for block number TEN, folks — incredible technique!"'
    ]),
    parent_script: '"Let\'s see how tall we can make this. You put one on, then I put one on. Ready? You go first — pick a good strong one for the bottom."',
    fallback_if_refuses: 'Build a tower yourself and let them be the one who knocks it down. Destruction is deeply satisfying at this age, and once they\'ve knocked a few down, they usually want to build one to smash. That counts.',
    easier_version: 'Build side by side instead of sharing one tower. No turn-taking pressure, and they can copy your technique.',
    harder_version: null,
    why_it_works: 'Waiting for your turn, even for just a few seconds, is genuine patience practice. And the physical act of stacking — lining edges up, balancing, adjusting — builds hand control and spatial awareness. The counting sneaks in some early number sense too.',
    safety_note: null,
    category: 'cognitive',
  },
  {
    id: 'fallback-puppet-show',
    title: 'Sock Puppet Theatre',
    description: 'Raid the odd-sock drawer, draw on some faces, and put on a show together. Puppets let kids practise tricky social stuff — sharing, saying sorry, meeting someone new — without any real-world stakes.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'speech',
    play_style_tags: 'stories',
    routine_moment_tags: 'evening',
    time_minutes: 15,
    materials: 'Two odd socks (the rattier the better), a marker or felt-tip pen for faces, optional: googly eyes, buttons, yarn for hair, a sofa to hide behind as a "stage"',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Pull on a sock and draw two dots for eyes and a wobbly mouth. Say in a silly voice: "Hello! My name is Professor Sockface. Who are YOU?" Hand your child the other sock and a marker.',
      'Let them decorate their puppet however they want. Wonky eyes, three mouths, a scribble nose — it\'s all perfect.',
      'Start a simple scene with your puppet. Pick something familiar: "Professor Sockface is going to the shop. He needs to buy bananas but he can\'t find them anywhere! Can your puppet help?"',
      'Let your child take over the story. Follow their lead, even if it goes completely off the rails. If they get stuck, have your puppet ask their puppet a question.',
      'If they\'re into it, hide behind the sofa as a "stage" and perform for a stuffed animal audience.',
      'Leave the puppets somewhere visible — sock puppets have a way of reappearing at breakfast the next morning.'
    ]),
    parent_script: '"(In a high squeaky voice) Hello there! I\'m Professor Sockface and I\'m a bit confused. I can\'t remember where I left my shoes — which is funny because I\'m a sock! Do you think your puppet could help me?"',
    fallback_if_refuses: 'Use the puppet to talk to your child instead of talking directly. Kids who won\'t talk to you will sometimes chat happily with a puppet — it feels less direct. "Professor Sockface" can ask what they want for dinner or what happened at nursery.',
    easier_version: 'Skip the decorating — just put a sock on your hand and make it "talk." The simplest puppet is just your hand opening and closing.',
    harder_version: null,
    why_it_works: 'When a puppet says something, it doesn\'t feel like it "counts" the same way real words do — so kids will try out new phrases, work through scenarios, and practise conversations with much less self-consciousness than face-to-face.',
    safety_note: null,
    category: 'language',
  },
  {
    id: 'fallback-obstacle-course',
    title: 'Living Room Obstacle Course',
    description: 'Cushion stepping stones, a chair tunnel to crawl through, a tape line to balance on, and a pillow to jump over at the end. Time their runs — then let them rebuild it however they want.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'fewer_screens',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 15,
    materials: 'Sofa cushions, dining chairs, masking tape or painter\'s tape (for a balance line on the floor), a pillow for a jump landing zone, a timer on your phone',
    location: 'indoor',
    energy_level: 'high',
    steps_json: JSON.stringify([
      'Lay 4-5 sofa cushions in a wobbly path across the floor — these are stepping stones over "lava." Say: "Whatever you do, don\'t touch the floor — it\'s lava!"',
      'Set up two chairs with a gap to crawl through (the "tunnel"). Drape a blanket over for extra effect if you like.',
      'Stick a line of tape on the floor for a balance beam. About two metres is plenty.',
      'Put a pillow at the end as a landing pad for a victory jump.',
      'Walk through the course once yourself, narrating each bit: "Stepping stones, through the tunnel, walk the tightrope, and... JUMP!" Then say: "Your turn. I\'m timing you — ready, set, GO!"',
      'After three or four runs, hand them the power: "Now YOU design the course for ME." Whatever they build, do it with full commitment.'
    ]),
    parent_script: '"OK, here\'s the deal. The floor is lava, that\'s a tunnel, that\'s a tightrope, and at the end you jump onto the crash pad. I\'m timing you on my phone. Ready? Three... two... one... GO!"',
    fallback_if_refuses: 'Build the course and do it yourself — count your own time, huff and puff, dramatically struggle through the tunnel. Then casually say: "I got 14 seconds. I bet nobody could beat that." Walk away. Wait.',
    easier_version: 'Just the cushion stepping stones — no timer, no crawling, just "don\'t touch the lava" while moving across the room.',
    harder_version: null,
    why_it_works: 'This scratches the same itch as a screen — it\'s novel, exciting, and has a clear goal. But it also burns off physical energy, builds coordination, and gives kids a sense of accomplishment that outlasts the dopamine hit of another YouTube video.',
    safety_note: 'Make sure chairs can\'t tip over. Move anything sharp or hard away from the landing zone. Bare feet grip better than socks.',
    category: 'physical',
  },
  {
    id: 'fallback-bedtime-yoga',
    title: 'Sleepy Animal Yoga',
    description: 'Five gentle animal stretches that take your child from wiggly to winding down. Cat, butterfly, flamingo, sleepy bear, and curled-up hedgehog — each one a little calmer than the last.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'easier_bedtime',
    play_style_tags: 'routine',
    routine_moment_tags: 'bedtime',
    time_minutes: 8,
    materials: 'Nothing — just a bit of floor space next to their bed, and maybe a blanket to lie on',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Start standing. Say: "Let\'s be five sleepy animals before bed. First — a cat who just woke up from a nap." Get on hands and knees, arch your back up like a stretching cat, then dip it down. Do it three times, slow.',
      'Sit down on the floor together. "Now we\'re butterflies drying our wings in the sun." Feet together, knees out, gently flap your knees up and down. Breathe in when knees go up, out when they come down.',
      'Stand on one leg. "Flamingo! Can you balance without falling in the pond?" Hold arms out wide. Wobbling and giggling is the whole point.',
      '"Now we\'re a tired bear going back to our cave." Stand up, then slowly fold forward, letting your arms hang heavy like a bear\'s paws. Sway gently side to side.',
      '"Last one. We\'re hedgehogs curling up for winter." Lie down and curl into the smallest, tightest ball you can. Whisper: "Tiny hedgehog... so cosy... so sleepy..."',
      'Unroll slowly. Lie flat and take three big breaths together. If they\'re in bed now, tuck them in and say: "Even the hedgehog is asleep."'
    ]),
    parent_script: '"Time for sleepy animal yoga. We\'re going to be five animals, and each one is a bit sleepier than the last. First — show me your best cat stretch. Big stretch... biiiiig stretch... ahhhh."',
    fallback_if_refuses: 'Do the poses yourself beside their bed, narrating in a soft, slow voice: "I\'m a stretchy cat... now I\'m a butterfly..." Don\'t ask them to join. The gentle movement and quiet voice often pull them in. If they just watch from bed, that\'s fine — they\'re still winding down.',
    easier_version: 'Do just the last two poses lying in bed — sleepy bear (stretch arms up, then flop) and curled-up hedgehog (curl into a ball). Two minutes, done.',
    harder_version: null,
    why_it_works: 'Slow, predictable movements with deep breathing tell the body it\'s safe to relax. Moving through a sequence — especially one that gets progressively calmer — is much more effective at winding down than just saying "calm down please."',
    safety_note: null,
    category: 'routine',
  },
  {
    id: 'fallback-magic-drawing',
    title: 'Secret Picture Painting',
    description: 'Draw an invisible picture with a white crayon on white paper, then hand your child the watercolours and watch their face when the hidden picture magically appears under the paint.',
    age_min: 2,
    age_max: 6,
    goal_tags: 'independent_play',
    play_style_tags: 'building',
    routine_moment_tags: 'morning',
    time_minutes: 12,
    materials: 'White paper, a white crayon (or a white candle stub — works even better), watercolour paints or watered-down food colouring, a chunky paintbrush, a cup of water, something to protect the table (newspaper, a bin bag, an old towel)',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'While your child isn\'t looking (or is busy with something else for a moment), press hard with a white crayon on white paper and draw something they\'ll recognise — a star, their initial, a cat face, a heart.',
      'Set out the paints, a brush, and the cup of water. Put the paper in front of them and say: "There\'s a secret picture hiding on this paper. The only way to find it is to paint over it."',
      'Let them paint however they want. As the colour goes over the wax, the hidden picture appears. Watch their face — this bit is genuinely delightful.',
      'Say: "You found it! It was a star! Want to make one for me now?" Hand them the white crayon and a fresh sheet.',
      'Let them draw their own secret picture (they\'ll press really hard, which is great for hand strength), then you paint over it to "find" it.',
      'Keep going as long as they\'re interested. This one has surprisingly long staying power.'
    ]),
    parent_script: '"I hid a secret picture on this paper. You can\'t see it yet — but if you paint over it, it\'ll magically appear. Grab the brush and let\'s find out what it is!"',
    fallback_if_refuses: 'Skip the secret picture part and just set out the watercolours for free painting. Most kids can\'t resist an open paint set. You can always try the hidden picture trick another day when the moment is right.',
    easier_version: 'You do all the drawing; they just paint to reveal. For very young ones, use a fat candle stub instead of a crayon — it\'s easier to grip and leaves a better wax resist.',
    harder_version: null,
    why_it_works: 'The surprise of watching something invisible appear holds attention far longer than regular painting. And pressing hard with the crayon, then controlling a wet brush across the page, builds the hand strength and control they\'ll need for writing.',
    safety_note: 'Cover your table and nearby floor — watercolours are washable but enthusiastic toddler painting reaches further than you\'d expect. Roll sleeves up or use an old shirt as a smock.',
    category: 'creative',
  },
  {
    id: 'fallback-puddle-splash',
    title: 'Puddle Kitchen',
    description: 'Head outside with cups, a funnel, and a spoon. Your child becomes a "chef" — stirring puddle soup, pouring between containers, testing what floats and what sinks. Messy, absorbing, and surprisingly long-lasting.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'independent_play',
    play_style_tags: 'moving',
    routine_moment_tags: 'afternoon',
    time_minutes: 15,
    materials: 'Wellies and clothes you don\'t mind getting wet, 2-3 cups or containers of different sizes, a funnel if you have one, a spoon for stirring, a few small items to test (leaf, stone, stick, bottle cap, pine cone)',
    location: 'outdoor',
    energy_level: 'medium',
    steps_json: JSON.stringify([
      'Kit up: wellies, old clothes, jacket if it\'s chilly. Accept in advance that they will get wet. Say: "We\'re going to be puddle chefs today. Chef\'s hat on!"',
      'Find a puddle, or fill a washing-up bowl with water outside. Set out the cups, funnel, and spoon nearby.',
      'Start the play: "First, we need to make puddle soup. Can you stir it with the spoon? Now pour some into this cup — is it full yet?"',
      'Introduce floating and sinking: "Chef\'s challenge — which ingredients float in our soup?" Drop in a leaf (floats!), then a stone (sinks!). Let them test other items.',
      'Step back. Once they\'re pouring between containers and dropping things in, most children will happily play for 10-15 minutes without needing you to direct.',
      'When it\'s time to go in, give a two-minute warning: "Two more pours and then we go inside for warm socks." Follow through calmly.'
    ]),
    parent_script: '"We\'re puddle chefs today! First job — pour some water into this cup. Is it full? Now pour it into the big cup. Does it fill up? Let\'s make soup — what should we add? How about this leaf?"',
    fallback_if_refuses: 'Skip the structured stuff entirely. Just stomp in the puddle together. Once they\'re already outside and already wet, the cups and pouring often happen on their own. The goal is getting them outdoors — everything else follows.',
    easier_version: 'Just splash and stomp — no cups, no pouring, no science. That\'s plenty for younger toddlers and rainy days when you just need to get wiggles out.',
    harder_version: null,
    why_it_works: 'Water is naturally mesmerising for young kids. Pouring between containers is one of the best ways they learn about "more and less," "full and empty," and "heavy and light" — all foundational maths concepts that stick better through hands-on play than flashcards.',
    safety_note: 'Stay within arm\'s reach any time there\'s water involved. Get them into dry clothes quickly afterwards so they don\'t get cold.',
    category: 'outdoor',
  },
  {
    id: 'fallback-feelings-faces',
    title: 'Feelings Faces Gallery',
    description: 'Draw big blank circles on paper and turn them into faces together — happy, grumpy, surprised, silly, sleepy. Then stick them on the fridge so your child can point to how they\'re feeling when words aren\'t enough.',
    age_min: 2,
    age_max: 5,
    goal_tags: 'calmer_transitions',
    play_style_tags: 'building',
    routine_moment_tags: 'anytime',
    time_minutes: 10,
    materials: 'Paper (one sheet is enough), crayons or markers, tape or a magnet to stick them on the fridge',
    location: 'indoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Draw 5-6 big empty circles on a sheet of paper. (If you\'re feeling fancy, cut them out.) Say: "We\'re going to make a feelings gallery for the fridge."',
      'Start with an easy one: "Can you draw a happy face? What do happy eyes look like? What about the mouth?" Draw yours alongside — it doesn\'t need to be good.',
      'Move to other feelings: grumpy (eyebrows down, mouth like a zigzag), surprised (big round mouth, wide eyes), silly (tongue sticking out), sleepy (droopy eyes, yawning mouth).',
      'After each one, make the face together. "Show me your grumpy face! Grrrr. Now show me your surprised face! OH!" This part usually gets giggly.',
      'Tape them to the fridge at your child\'s eye level. Say: "Now whenever you\'re feeling something big, you can point to the face that matches. Even if you can\'t find the words, you can show me."',
      'Over the next few days, use them yourself: "I\'m feeling a bit grumpy right now — see, that face there? But I think a cup of tea will help." Modelling this is the most powerful part.'
    ]),
    parent_script: '"Let\'s draw some feelings faces for the fridge. You know what happy looks like — can you draw it? Big smile! Now what about a grumpy face? Show me with YOUR face first — oh, that\'s a very good grumpy face!"',
    fallback_if_refuses: 'Draw the faces yourself and let them just colour them in, add stickers, or circle the one that matches how they feel right now. Even pointing at a pre-drawn face is a win — the goal is giving them a way to communicate feelings, not creating art.',
    easier_version: 'Draw the faces yourself and print or cut them out. They just need to point to one. You can also use emoji stickers if you have them.',
    harder_version: null,
    why_it_works: 'Young kids feel big feelings but often can\'t name them yet — which makes the feelings scarier and harder to manage. Having a face to point at gives them a way to say "I feel THIS" without needing the vocabulary. And once a feeling is named, it\'s already a little easier to handle.',
    safety_note: null,
    category: 'emotional',
  },
  {
    id: 'fallback-shadow-tracing',
    title: 'Shadow Detectives',
    description: 'Place toys in a sunny spot and trace around their shadows with chalk or crayons. Come back an hour later and the shadows have moved — genuine real-world magic that your child figured out on their own.',
    age_min: 3,
    age_max: 6,
    goal_tags: 'focus',
    play_style_tags: 'building',
    routine_moment_tags: 'morning',
    time_minutes: 12,
    materials: 'A few small toys or figures (dinosaurs, dolls, and kitchen utensils all cast great shadows), chalk for outdoors or paper and crayons for a sunny windowsill, optional: a pencil to write the time next to each tracing',
    location: 'outdoor',
    energy_level: 'low',
    steps_json: JSON.stringify([
      'Find a sunny spot — outside on a path or inside near a bright window. Morning or late afternoon shadows are longest and most dramatic.',
      'Stand a toy up so it casts a clear shadow. Say: "Look — your dinosaur has a shadow friend! Let\'s draw around it so we can remember where it was."',
      'Trace around the shadow carefully with chalk or crayon. Write the time next to it (or draw a clock face if they\'re interested in that).',
      'Try 3-4 different toys. Ask: "Which toy makes the funniest shadow? What if you hold it at a different angle?"',
      'Leave the toys in place. Say: "I bet something interesting happens to the shadows later. Let\'s come back after lunch and check." Set an actual timer or alarm so you remember.',
      'Come back an hour later. The shadows have moved! Trace them again in a different colour. Say: "The shadow moved! But we didn\'t move the dinosaur... what do you think happened?"'
    ]),
    parent_script: '"Your dinosaur has a shadow! Can you trace around it with the chalk? Carefully, right around the edges... brilliant! Now here\'s the mystery — I think the shadow is going to MOVE. Let\'s come back after lunch and see."',
    fallback_if_refuses: 'Trace their own shadow on the pavement instead — have them strike a pose while you draw around it. Or just play with shadows: make hand puppets on the wall, see whose shadow is tallest, try to "step on" each other\'s shadows.',
    easier_version: 'Skip the tracing and just play with shadows — make shapes with your hands, chase each other\'s shadows, notice how they get longer near the end of the day.',
    harder_version: null,
    why_it_works: 'Tracing around a small shape takes careful hand control and sustained focus. And discovering that shadows move on their own plants a genuine "why does that happen?" question that they figured out through their own observation, not because someone told them.',
    safety_note: 'Hats and sun cream if you\'re outside for more than a few minutes. Move into the shade if anyone\'s getting pink.',
    category: 'cognitive',
  },
];
